@props(['item'])
@php $progress=$item['progress'];$percent=$progress?intdiv($progress[0]*100,max(1,$progress[1])):0; @endphp
<article class="rounded-[18px] border border-white/[.07] bg-[#3c354a] p-4 shadow-[0_16px_36px_rgba(17,10,27,.12)]">
    <div class="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="text-xs font-medium text-cyan-200">{{ $item['title'] }}</span>@if(in_array($item['priority'],['urgent','high']))<span class="rounded-full bg-rose-300/10 px-2 py-0.5 text-[10px] text-rose-200">{{ \App\Support\SupportPresentation::priority($item['priority']) }}</span>@endif</div><h3 class="mt-1 font-semibold">{{ $item['investor_name'] }}</h3>@if($item['amount'])<p class="mt-1 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($item['amount']) }} <span class="text-xs font-normal text-[#9080ba]">{{ $item['currency'] }}</span></p>@else<p class="mt-1 text-sm text-[#aaa0b3]">{{ $item['subtitle'] }}</p>@endif<p class="mt-2 text-xs text-[#9080ba]">{{ $item['status'] }} · Возраст: {{ $item['created_at']->diffForHumans(now(),true) }}</p></div>
        @if($item['target']==='ticket')<button wire:click="openTicket({{ $item['source_id'] }})" class="shrink-0 cursor-pointer rounded-xl bg-cyan-300/10 px-4 py-2 text-sm text-cyan-100">{{ $item['action'] }}</button>@else<a href="{{ $item['target'] }}" class="shrink-0 rounded-xl bg-gradient-to-r from-purple-500/20 to-cyan-400/15 px-4 py-2 text-center text-sm text-cyan-100">{{ $item['action'] }}</a>@endif
    </div>
    @if($progress)<div class="mt-4"><div class="flex justify-between text-xs"><span class="text-[#9080ba]">Проверка</span><span>{{ $progress[0] }}/{{ $progress[1] }}</span></div><div class="mt-2 h-1.5 overflow-hidden rounded-full bg-[#292235]"><div class="h-full rounded-full bg-gradient-to-r from-[#aa68e8] to-cyan-300" style="width: {{ $percent }}%"></div></div>@if($item['waiting'])<div class="mt-3"><p class="text-[10px] uppercase tracking-wide text-[#776b86]">Ожидает</p><ul class="mt-1 space-y-1 text-xs text-[#a99dad]">@foreach($item['waiting'] as $waiting)<li>· {{ $waiting }}</li>@endforeach</ul></div>@endif</div>@endif
    @if($item['finance']||$item['timeline'])
        <details class="mt-4 border-t border-white/[.06] pt-3"><summary class="cursor-pointer text-xs text-purple-200">Детали операции и история</summary><div class="mt-3 grid gap-4 lg:grid-cols-2">
            @if($item['finance'])<dl class="grid grid-cols-2 gap-3 text-xs">@foreach([['Сумма',$item['finance']['gross']],['Комиссия',$item['finance']['fee']],['После комиссии',$item['finance']['net']]] as [$label,$value])<div><dt class="text-[#81748f]">{{ $label }}</dt><dd class="mt-1">{{ \App\Support\MoneyFormatter::format($value) }} {{ $item['currency'] }}</dd></div>@endforeach<div><dt class="text-[#81748f]">Тип комиссии</dt><dd class="mt-1">{{ \App\Support\FeeRulePresentation::economicType($item['finance']['economic']) }}</dd></div><div><dt class="text-[#81748f]">Плательщик</dt><dd class="mt-1">{{ \App\Support\FeeRulePresentation::payer($item['finance']['payer']??'') }}</dd></div></dl>@endif
            @if($item['timeline'])<ol class="space-y-2 border-l border-purple-300/15 pl-4">@foreach($item['timeline'] as $event)<li><p class="text-xs font-medium">{{ $event['label'] }}</p><p class="text-[10px] text-[#81748f]">{{ $event['time']->format('d.m.Y H:i') }} · {{ $event['actor'] }}</p></li>@endforeach</ol>@endif
        </div></details>
    @endif
</article>
