@php
    if (!class_exists('MoneyFormatter', false)) class_alias(\App\Support\MoneyFormatter::class, 'MoneyFormatter');
    $isCapitalization = $dialog === 'capitalization';
    $isCapital = $dialog === 'capital';
    $amount = $isCapitalization ? $capitalizationAmount : $withdrawalAmount;
    $preview = $isCapitalization ? $capitalizationPreview : $withdrawalPreview;
    $valid = $isCapitalization ? $capitalizationValid : $withdrawalValid;
    $operationTitle = $isCapitalization ? 'Перевести в капитал' : ($isCapital ? 'Вывести капитал' : 'Вывести дивиденды');
    $operationHint = $isCapitalization ? 'Создание новой инвестиции' : 'Создание заявки на вывод средств';
@endphp
<div x-data="{ modalOpen: true, closeModal() { this.modalOpen = false; this.$wire.closeDialog(); } }" x-show="modalOpen" x-on:click.self="closeModal()" x-on:keydown.escape.window="closeModal()" class="fixed inset-0 z-[70] flex items-end justify-center bg-[#16101f]/85 p-4 backdrop-blur-sm sm:items-center">
    <div role="dialog" aria-modal="true" aria-labelledby="financial-dialog-title" class="max-h-[92vh] w-full max-w-[490px] overflow-y-auto rounded-[22px] border border-white/10 bg-[#3c354a] p-5 shadow-2xl sm:p-6">
        <div class="flex items-start justify-between gap-4"><div><p class="text-[10px] uppercase tracking-[.16em] text-[#867897]">Шаг {{ $dialogStep === 'confirm' ? '2 из 2' : '1 из 2' }}</p><h3 id="financial-dialog-title" class="mt-1 text-xl font-semibold">{{ $operationTitle }}</h3><p class="mt-1 text-xs text-[#9b8dac]">{{ $operationHint }}</p></div><button type="button" x-on:click="closeModal()" aria-label="Закрыть" class="flex size-9 shrink-0 cursor-pointer items-center justify-center rounded-xl bg-white/5 text-lg">×</button></div>

        @if($dialogError)<div role="alert" class="mt-4 rounded-2xl border border-rose-300/15 bg-rose-400/[.07] px-4 py-3 text-sm text-rose-200">{{ $dialogError }}</div>@endif

        @if($dialogStep === 'confirm')
            <div class="mt-5 rounded-2xl border border-purple-300/10 bg-[#2c2538] p-4"><p class="text-xs font-medium text-[#b9aec5]">Подтвердите операцию</p><dl class="mt-3 space-y-2.5 text-sm"><div class="flex justify-between gap-4"><dt class="text-[#91849f]">Операция</dt><dd class="text-right">{{ $operationTitle }}</dd></div><div class="flex justify-between gap-4"><dt class="text-[#91849f]">Сумма</dt><dd>{{ MoneyFormatter::format($amount) }} USDT</dd></div><div class="flex justify-between gap-4"><dt class="text-[#91849f]">Комиссия</dt><dd>{{ MoneyFormatter::format($preview['fee_amount'] ?? '0') }} USDT</dd></div><div class="flex justify-between gap-4"><dt class="text-[#91849f]">Итог</dt><dd class="font-medium text-cyan-100">{{ MoneyFormatter::format($preview['net_amount'] ?? '0') }} USDT</dd></div>@if(!$isCapitalization && $withdrawalDetail)<div class="flex justify-between gap-4"><dt class="text-[#91849f]">Реквизиты</dt><dd class="max-w-52 text-right">{{ $withdrawalDetail->network }} · <span class="break-all">{{ $withdrawalDetail->address }}</span>@if($withdrawalDetail->memo)<span class="mt-1 block text-xs text-[#91849f]">Memo/Tag: {{ $withdrawalDetail->memo }}</span>@endif</dd></div>@endif @if($isCapitalization)<div class="flex justify-between gap-4"><dt class="text-[#91849f]">Ставка</dt><dd>{{ MoneyFormatter::format($term?->monthly_rate) }}%</dd></div><div class="flex justify-between gap-4"><dt class="text-[#91849f]">Блокировка</dt><dd>{{ $term?->lock_months ?? 0 }} мес.</dd></div>@endif</dl></div>
            <div class="mt-5 grid grid-cols-2 gap-3"><button type="button" wire:click="backToDialogForm" class="cursor-pointer rounded-xl border border-white/10 px-4 py-3 text-sm">Назад</button><button type="button" wire:click="{{ $isCapitalization ? 'capitalize' : ($isCapital ? 'requestCapitalWithdrawal' : 'requestDividendWithdrawal') }}" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#8d61ed] to-[#4ebdd5] px-4 py-3 text-sm font-semibold">Подтвердить</button></div>
        @else
            @if($isCapitalization)
                <div class="mt-5 rounded-2xl bg-[#2c2538] p-4"><p class="text-xs text-[#9b8dac]">Доступно дивидендов</p><p class="mt-1 text-xl font-semibold">{{ MoneyFormatter::format($summary['availableDividends']) }} USDT</p></div>
            @elseif($isCapital)
                <div class="mt-5 grid grid-cols-3 gap-2"><div class="rounded-xl bg-[#2c2538] p-3"><p class="text-[10px] text-[#9b8dac]">Общий капитал</p><p class="mt-1 text-sm font-semibold">{{ MoneyFormatter::format($summary['capital']) }}</p></div><div class="rounded-xl bg-[#2c2538] p-3"><p class="text-[10px] text-[#9b8dac]">Заблокировано</p><p class="mt-1 text-sm font-semibold">{{ MoneyFormatter::format($summary['lockedCapital']) }}</p></div><div class="rounded-xl bg-[#2c2538] p-3"><p class="text-[10px] text-[#9b8dac]">Доступно</p><p class="mt-1 text-sm font-semibold text-cyan-100">{{ MoneyFormatter::format($summary['availableCapital']) }}</p></div></div>
                @if($nearestUnlock)<p class="mt-2 text-xs text-[#9486a5]">Ближайшая разблокировка: {{ \Carbon\Carbon::parse($nearestUnlock)->format('d.m.Y') }}</p>@endif
            @else
                <div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-xl bg-[#2c2538] p-3"><p class="text-xs text-[#9b8dac]">Доступно</p><p class="mt-1 text-lg font-semibold">{{ MoneyFormatter::format($summary['availableDividends']) }} USDT</p></div><div class="rounded-xl bg-[#2c2538] p-3"><p class="text-xs text-[#9b8dac]">В резерве</p><p class="mt-1 text-lg font-semibold">{{ MoneyFormatter::format($operationChanges['dividendReserved']) }} USDT</p></div></div>
            @endif

            @if($isCapital && $summary['availableCapital'] === '0.00000000')
                <div class="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-4 text-sm text-amber-100"><p class="font-medium">Капитал временно недоступен к выводу.</p>@if($nearestUnlock)<p class="mt-1 text-xs opacity-80">Доступ появится после {{ \Carbon\Carbon::parse($nearestUnlock)->format('d.m.Y') }}.</p>@endif</div>
            @else
                <label for="operation-amount" class="mt-4 block text-xs text-[#a99abc]">{{ $isCapitalization ? 'Сумма капитализации' : 'Сумма вывода' }}</label><div class="relative mt-1"><input id="operation-amount" autofocus wire:model.live.debounce.300ms="{{ $isCapitalization ? 'capitalizationAmount' : 'withdrawalAmount' }}" inputmode="decimal" placeholder="0.00" class="h-[50px] w-full rounded-xl border border-white/10 bg-[#292235] px-3 pr-28 text-base"><span class="pointer-events-none absolute right-3 top-2 text-xs text-[#82758f]">USDT</span><button type="button" wire:click="{{ $isCapitalization ? 'useAllDividends' : 'useAllWithdrawal' }}" class="absolute bottom-1.5 right-2 cursor-pointer rounded-lg bg-white/5 px-2 py-1 text-[10px] text-cyan-200">{{ $isCapital ? 'Максимум' : 'Вся сумма' }}</button></div>
                @error($isCapitalization ? 'capitalizationAmount' : 'withdrawalAmount')<p class="mt-2 text-xs text-rose-300">{{ $message }}</p>@enderror

                @if(!$isCapitalization)
                    @if(!$withdrawalDetail)<div class="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-4 text-sm text-amber-100"><p>Администратор ещё не назначил реквизиты для вывода средств.</p></div>
                    @else<div class="mt-4 rounded-xl bg-white/[.03] p-3 text-xs"><p><span class="text-[#8e819d]">Валюта:</span> {{ $withdrawalDetail->currency }}</p><p class="mt-1"><span class="text-[#8e819d]">Сеть:</span> {{ $withdrawalDetail->network }}</p><div class="mt-1 flex items-center gap-2"><p class="min-w-0 flex-1 break-all"><span class="text-[#8e819d]">Адрес:</span> {{ $withdrawalDetail->address }}</p><button type="button" onclick="navigator.clipboard.writeText(@js($withdrawalDetail->address))" class="shrink-0 cursor-pointer rounded-lg border border-cyan-200/15 px-2 py-1 text-cyan-200">Copy</button></div>@if($withdrawalDetail->memo)<p class="mt-1 break-all"><span class="text-[#8e819d]">Memo/Tag:</span> {{ $withdrawalDetail->memo }}</p>@endif<p class="mt-2 text-[10px] text-[#8e819d]">Реквизиты назначены администратором и доступны только для просмотра.</p></div>@endif
                @endif

                <div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Комиссия</p><p class="mt-1">{{ MoneyFormatter::format($preview['fee_amount'] ?? '0') }} USDT</p></div><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">{{ $isCapitalization ? 'Будет добавлено в капитал' : 'К выплате' }}</p><p class="mt-1 text-cyan-200">{{ MoneyFormatter::format($preview['net_amount'] ?? '0') }} USDT</p></div></div>

                <div class="mt-4 rounded-2xl border border-white/[.06] bg-[#2c2538] p-4"><p class="text-xs font-medium text-[#b9aec5]">После операции</p>@if($isCapitalization)<div class="mt-3 space-y-2 text-xs"><div class="flex justify-between"><span class="text-[#91849f]">Инвестиционный капитал</span><span>{{ MoneyFormatter::format($summary['capital']) }} → {{ MoneyFormatter::format($operationChanges['capitalAfter']) }} USDT</span></div><div class="flex justify-between"><span class="text-[#91849f]">Доступно дивидендов</span><span>{{ MoneyFormatter::format($summary['availableDividends']) }} → {{ MoneyFormatter::format($operationChanges['dividendsAfterCapitalization']) }} USDT</span></div></div>@elseif($isCapital)<div class="mt-3 space-y-2 text-xs"><div class="flex justify-between"><span class="text-[#91849f]">Доступный капитал</span><span>{{ MoneyFormatter::format($summary['availableCapital']) }} → {{ MoneyFormatter::format($operationChanges['availableCapitalAfter']) }} USDT</span></div><div class="flex justify-between"><span class="text-[#91849f]">Зарезервировано</span><span>{{ MoneyFormatter::format($operationChanges['capitalReserved']) }} → {{ MoneyFormatter::format($operationChanges['capitalReservedAfter']) }} USDT</span></div></div>@else<div class="mt-3 space-y-2 text-xs"><div class="flex justify-between"><span class="text-[#91849f]">Доступно дивидендов</span><span>{{ MoneyFormatter::format($summary['availableDividends']) }} → {{ MoneyFormatter::format($operationChanges['dividendsAfterWithdrawal']) }} USDT</span></div><div class="flex justify-between"><span class="text-[#91849f]">Зарезервировано</span><span>{{ MoneyFormatter::format($operationChanges['dividendReserved']) }} → {{ MoneyFormatter::format($operationChanges['dividendReservedAfter']) }} USDT</span></div></div>@endif</div>

                @if($isCapitalization)<div class="mt-4 grid grid-cols-2 gap-2 text-xs"><div class="rounded-xl bg-white/[.03] p-3"><span class="text-[#91849f]">Ставка</span><p class="mt-1">{{ MoneyFormatter::format($term?->monthly_rate) }}%</p></div><div class="rounded-xl bg-white/[.03] p-3"><span class="text-[#91849f]">Блокировка</span><p class="mt-1">{{ $term?->lock_months ?? 0 }} мес.</p></div><div class="rounded-xl bg-white/[.03] p-3"><span class="text-[#91849f]">Разблокировка</span><p class="mt-1">{{ $capitalizationUnlockDate?->format('d.m.Y') ?? 'Без блокировки' }}</p></div><div class="rounded-xl bg-white/[.03] p-3"><span class="text-[#91849f]">Начало начислений</span><p class="mt-1">{{ now()->addDay()->format('d.m.Y') }}</p></div></div><div class="mt-3 space-y-2 text-[11px] leading-4 text-[#9d91aa]"><p>Капитализированная сумма станет новой инвестицией и перестанет быть доступна для вывода как дивиденды.</p><p>Начисления по новой инвестиции начинаются со следующего календарного дня.</p></div>
                @elseif($isCapital)<div class="mt-3 text-[11px] leading-4 text-[#9d91aa]"><p>До фактической выплаты сумма будет зарезервирована. Инвестиционный капитал уменьшается только после выполнения выплаты.</p>@if($term && !$term->partial_withdrawal_allowed)<p class="mt-2 text-amber-200">Частичный вывод капитала запрещён условиями счёта.</p>@endif @if($term && $term->minimum_balance !== '0.00000000')<p class="mt-2 text-amber-200">После вывода на счёте должно остаться не менее {{ MoneyFormatter::format($term->minimum_balance) }} USDT.</p>@endif</div>
                @else<p class="mt-3 text-[11px] leading-4 text-[#9d91aa]">После отправки создаётся заявка на вывод. Выплата будет выполнена после обработки администратором.</p>@endif

                <button type="button" wire:click="continueOperation" @disabled(!$valid || (!$isCapitalization && !$withdrawalDetail)) class="mt-5 w-full cursor-pointer rounded-xl bg-gradient-to-r from-[#8d61ed] to-[#4ebdd5] px-4 py-3 font-semibold disabled:cursor-not-allowed disabled:opacity-40">Продолжить</button>
            @endif
        @endif
    </div>
</div>
