<div class="mx-auto max-w-[1800px]">
    <div class="mb-5 flex items-end justify-between gap-4">
        <div><h2 class="text-[24px] font-semibold tracking-tight text-white">Финансовый обзор</h2><p class="mt-1 text-xs text-[#8f82a6]">Актуальные данные платформы на {{ now()->format('d.m.Y') }}</p></div>
        <div class="hidden items-center gap-2 text-xs text-[#9486ad] sm:flex"><span class="size-2 rounded-full bg-cyan-300 shadow-[0_0_12px_#67e8f9]"></span> Данные обновлены</div>
    </div>

    <section class="mb-4 rounded-[20px] border border-white/[.07] bg-[#342c43] p-4 sm:p-5">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-medium text-cyan-200">CEO Analytics v1</p><h3 class="mt-1 text-lg font-semibold">Управленческая аналитика</h3></div><div class="flex max-w-full gap-1 overflow-x-auto rounded-xl bg-[#292236] p-1">@foreach(['today'=>'Сегодня','7'=>'7 дней','month'=>'Месяц','year'=>'Год'] as $period=>$label)<button type="button" wire:click="setAnalyticsPeriod('{{ $period }}')" class="shrink-0 cursor-pointer rounded-lg px-3 py-2 text-xs {{ $analyticsPeriod===$period?'bg-purple-400/20 text-purple-100':'text-[#9080ba]' }}">{{ $label }}</button>@endforeach</div></div>
        <div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            <div class="rounded-[18px] bg-white/[.025] p-4"><p class="text-xs text-[#9588aa]">Общий капитал</p><div class="mt-2 space-y-1">@forelse($ceoPortfolio['capital'] as $currency=>$amount)<p class="text-xl font-semibold">{{ \App\Support\MoneyFormatter::format($amount) }} <span class="text-[10px] font-normal text-[#776a8e]">{{ $currency }}</span></p>@empty<p class="text-xl font-semibold">0.00 USDT</p>@endforelse</div></div>
            <div class="rounded-[18px] bg-white/[.025] p-4"><p class="text-xs text-[#9588aa]">Активные инвесторы</p><p class="mt-2 text-xl font-semibold">{{ $ceoPortfolio['active_investors'] }}</p><p class="mt-1 text-[10px] text-[#776a8e]">Инвестиций: {{ $ceoPortfolio['investments'] }}</p></div>
            <div class="rounded-[18px] bg-white/[.025] p-4"><p class="text-xs text-[#9588aa]">Средняя инвестиция</p>@forelse($ceoPortfolio['average_investment'] as $currency=>$amount)<p class="mt-2 text-xl font-semibold">{{ \App\Support\MoneyFormatter::format($amount) }} <span class="text-[10px] font-normal text-[#776a8e]">{{ $currency }}</span></p>@empty<p class="mt-2 text-xl font-semibold">0.00 USDT</p>@endforelse</div>
            <div class="rounded-[18px] bg-white/[.025] p-4"><p class="text-xs text-[#9588aa]">Новые инвестиции</p><p class="mt-2 text-xl font-semibold text-cyan-100">+{{ array_sum($ceoPortfolio['new_investments']) }}</p></div>
        </div>
    </section>

    <section class="mb-4 grid gap-4 xl:grid-cols-2">
        <article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><h3 class="font-semibold">Денежный поток</h3><div class="mt-4 grid gap-3 sm:grid-cols-3">@foreach([['Пополнения','deposits','+','text-cyan-100'],['Выводы','withdrawals','−','text-purple-100'],['Чистый поток','net','', 'text-white']] as [$label,$key,$sign,$color])<div class="rounded-xl bg-white/[.025] p-3"><p class="text-xs text-[#9588aa]">{{ $label }}</p>@forelse($ceoCashFlow[$key] as $currency=>$amount)<p class="mt-2 font-semibold {{ $color }}">{{ $sign }}{{ \App\Support\MoneyFormatter::format($amount) }} <small class="font-normal">{{ $currency }}</small></p>@empty<p class="mt-2 font-semibold">0.00 USDT</p>@endforelse</div>@endforeach</div></article>
        <article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><h3 class="font-semibold">Доход платформы</h3><div class="mt-4 grid gap-3 sm:grid-cols-3">@foreach([['Доход платформы','platform_revenue','text-cyan-100'],['Расходы провайдера','provider_costs','text-amber-100'],['Неклассифицировано','unclassified_fees','text-[#aaa0b3]']] as [$label,$key,$color])<div class="rounded-xl bg-white/[.025] p-3"><p class="text-[10px] text-[#9588aa]">{{ $label }}</p>@forelse($ceoRevenue[$key] as $currency=>$amount)<p class="mt-2 text-sm font-semibold {{ $color }}">{{ \App\Support\MoneyFormatter::format($amount) }} {{ $currency }}</p>@empty<p class="mt-2 text-sm">0.00 USDT</p>@endforelse</div>@endforeach</div><div class="mt-3 flex flex-wrap gap-2">@foreach($ceoRevenue['by_operation'] as $operation=>$values)<span class="rounded-lg bg-purple-300/[.07] px-2.5 py-1.5 text-[10px] text-[#bcaec8]">{{ \App\Support\InvestorPresentation::type($operation) }}: {{ \App\Support\MoneyFormatter::format($values['platform_revenue']['USDT']??'0') }} USDT</span>@endforeach</div></article>
    </section>

    <section class="mb-4 grid gap-4 lg:grid-cols-3">@foreach([['Рост капитала','capital','#bb7ff5'],['Начисления','accruals','#70d7e8'],['Доход платформы','revenue','#fa9bae']] as [$label,$key,$color])<article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4"><h3 class="text-sm font-semibold">{{ $label }}</h3><div class="relative mt-3 h-36 overflow-hidden"><div class="absolute inset-1 grid grid-rows-3"><i class="border-t border-white/[.05]"></i><i class="border-t border-white/[.05]"></i><i class="border-t border-white/[.05]"></i></div><svg viewBox="0 0 620 150" preserveAspectRatio="none" class="relative h-full w-full"><polyline points="{{ $ceoTrendPoints[$key] }}" fill="none" stroke="{{ $color }}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div class="mt-1 flex justify-between text-[8px] text-[#746781]">@foreach($ceoTrendLabels->filter(fn($v,$i)=>$i===0||$i===$ceoTrendLabels->count()-1) as $labelDate)<span>{{ $labelDate }}</span>@endforeach</div></article>@endforeach</section>

    <section class="mb-4 grid gap-4 xl:grid-cols-[1.3fr_.7fr]"><article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><h3 class="font-semibold">Лучшие инвесторы</h3><div class="mt-4 space-y-2">@forelse($ceoRanking as $index=>$row)<div class="grid gap-2 rounded-xl bg-white/[.025] p-3 sm:grid-cols-[30px_1fr_repeat(3,minmax(110px,.65fr))] sm:items-center"><span class="text-sm text-purple-200">{{ $index+1 }}</span><div><p class="text-sm font-medium">{{ $row['investor']->user->name }}</p><p class="text-[10px] text-[#81748f]">{{ $row['investor']->code }}</p></div><p class="text-xs"><span class="text-[#81748f]">Капитал</span><br>{{ \App\Support\MoneyFormatter::format($row['invested_capital']) }} {{ $row['currency'] }}</p><p class="text-xs"><span class="text-[#81748f]">Начислено</span><br>{{ \App\Support\MoneyFormatter::format($row['accrued']) }} {{ $row['currency'] }}</p><p class="text-xs"><span class="text-[#81748f]">Доступно</span><br>{{ \App\Support\MoneyFormatter::format($row['available_balance']) }} {{ $row['currency'] }}</p></div>@empty<p class="text-sm text-[#9080ba]">Данных пока нет.</p>@endforelse</div></article><article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><h3 class="font-semibold">Требуют внимания</h3><div class="mt-4 space-y-2">@foreach([['Заявки ожидают обработки',$ceoRisks['pending_operations']],['Новые кошельки',$ceoRisks['new_wallets']],['Нет активности 30+ дней',$ceoRisks['inactive_investors']]] as [$label,$value])<div class="flex justify-between rounded-xl bg-amber-300/[.035] p-3 text-xs"><span class="text-[#b9aebf]">⚠ {{ $label }}</span><b class="text-amber-100">{{ $value }}</b></div>@endforeach @foreach($ceoRisks['large_withdrawals'] as $risk)<div class="rounded-xl bg-rose-300/[.035] p-3 text-xs"><p class="text-rose-100">⚠ Большой вывод {{ \App\Support\MoneyFormatter::format($risk['amount']) }} {{ $risk['currency'] }}</p><p class="mt-1 text-[10px] text-[#81748f]">{{ $risk['investor'] }}</p></div>@endforeach</div></article></section>

    <section class="mb-4 rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><div class="flex items-center justify-between"><div><h3 class="font-semibold">Инвестиционные программы</h3><p class="mt-1 text-xs text-[#9588aa]">Капитал и инвесторы по продуктам</p></div><a href="{{ route('admin.investment-programs.index') }}" class="text-xs text-cyan-200">Управление →</a></div><div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach($ceoPrograms as $row)<div class="rounded-xl bg-white/[.025] p-3"><p class="font-medium">{{ $row['program']->name }}</p><p class="mt-2 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($row['capital']) }} <small>{{ $row['currency'] }}</small></p><p class="mt-1 text-[10px] text-[#8f829f]">{{ $row['investors_count'] }} инвесторов · {{ $row['lots_count'] }} инвестиций</p></div>@endforeach</div></section>

    <section class="grid gap-4 xl:grid-cols-[1.02fr_.98fr]">
        <article class="relative min-h-[292px] overflow-hidden rounded-[24px] border border-[#c990f5]/20 bg-gradient-to-br from-[#6d48a2] via-[#573b82] to-[#352846] p-6 shadow-[0_24px_60px_rgba(20,12,32,.22)] sm:p-7">
            <div class="absolute -right-20 -top-24 size-72 rounded-full bg-[#c985ff]/20 blur-3xl"></div><div class="absolute -bottom-24 left-1/3 size-64 rounded-full bg-cyan-300/10 blur-3xl"></div><div class="absolute right-10 top-12 size-24 rotate-12 rounded-[28px] border border-white/10 bg-white/[.035]"></div>
            <div class="relative flex h-full flex-col">
                <div class="flex items-center justify-between"><div class="flex items-center gap-3"><div class="flex size-10 items-center justify-center rounded-2xl border border-white/15 bg-white/10 text-xs font-black">CM</div><div><p class="font-semibold">CEO Money</p><p class="text-[11px] text-[#d7b9ed]">Investment management</p></div></div><span class="rounded-xl border border-white/10 bg-black/10 px-3 py-1.5 text-[10px] uppercase tracking-[.16em] text-[#ddc4ef]">Portfolio</span></div>
                <div class="mt-8"><p class="text-xs text-[#d7b9ed]">Общий инвестиционный капитал</p><div class="mt-2 flex flex-wrap items-baseline gap-2"><span class="text-[32px] font-semibold tracking-[-.04em] sm:text-[38px]">{{ \App\Support\MoneyFormatter::format($summary['capital']) }}</span><span class="text-sm text-[#ddc4ef]">USDT</span></div></div>
                <div class="mt-auto grid grid-cols-2 gap-x-5 gap-y-4 border-t border-white/10 pt-5 sm:grid-cols-3">
                    <div><p class="text-[10px] uppercase tracking-wide text-[#cdb2df]">Активных инвесторов</p><p class="mt-1 text-lg font-semibold">{{ $summary['activeInvestors'] }}</p></div>
                    <div><p class="text-[10px] uppercase tracking-wide text-[#cdb2df]">Начислено за месяц</p><p class="mt-1 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($summary['monthAccrual']) }}</p></div>
                    <div class="col-span-2 sm:col-span-1"><p class="text-[10px] uppercase tracking-wide text-[#cdb2df]">Доступно к выплате</p><p class="mt-1 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($summary['availableDividends']) }}</p></div>
                </div>
            </div>
        </article>

        <article class="rounded-[24px] border border-white/[.07] bg-[#342c43]/90 p-5 shadow-[0_24px_60px_rgba(20,12,32,.16)] sm:p-6">
            <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-base font-semibold">Капитал и начисления</h3><p class="mt-1 text-xs text-[#9183a8]">Динамика текущего месяца</p></div><div class="flex rounded-xl bg-[#292236] p-1 text-[10px] text-[#887b9e]"><span class="rounded-lg px-2.5 py-1.5">1D</span><span class="rounded-lg px-2.5 py-1.5">1W</span><span class="rounded-lg bg-[#a768df] px-2.5 py-1.5 text-white shadow-lg shadow-purple-950/30">1M</span></div></div>
            <div class="mt-3 flex flex-wrap gap-4 text-[11px]"><span class="flex items-center gap-2 text-[#a99abb]"><i class="size-2 rounded-full bg-[#bb7ff5]"></i> Капитал</span><span class="flex items-center gap-2 text-[#a99abb]"><i class="size-2 rounded-full bg-cyan-300"></i> Начисления</span></div>
            <div class="relative mt-2 h-[190px] w-full overflow-hidden">
                <div class="absolute inset-2 grid grid-rows-4"><i class="border-t border-white/[.055]"></i><i class="border-t border-white/[.055]"></i><i class="border-t border-white/[.055]"></i><i class="border-t border-white/[.055]"></i></div>
                <svg viewBox="0 0 620 180" preserveAspectRatio="none" class="relative h-full w-full" aria-label="График капитала и начислений"><defs><linearGradient id="monthGlow" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#bb7ff5" stop-opacity=".25"/><stop offset="1" stop-color="#bb7ff5" stop-opacity="0"/></linearGradient><filter id="cyanGlow"><feGaussianBlur stdDeviation="2.5" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><polyline points="{{ $monthCapitalPoints }}" fill="none" stroke="#bb7ff5" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><polyline points="{{ $monthAccrualPoints }}" fill="none" stroke="#70d7e8" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" filter="url(#cyanGlow)"/></svg>
            </div>
        </article>
    </section>

    <section class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-5">
        @foreach($kpis as $index => [$label, $value, $points])
            <article class="relative overflow-hidden rounded-[19px] border border-white/[.065] bg-[#352e43] p-4 transition hover:-translate-y-0.5 hover:border-[#af73e6]/25">
                <div class="absolute right-0 top-0 h-20 w-24 bg-gradient-to-bl {{ $index % 2 ? 'from-cyan-300/[.06]' : 'from-purple-400/[.08]' }} to-transparent"></div>
                <div class="relative"><div class="flex items-center justify-between"><p class="text-[11px] text-[#9588aa]">{{ $label }}</p><span class="flex size-7 items-center justify-center rounded-xl bg-white/[.04] text-xs {{ $index % 2 ? 'text-cyan-300' : 'text-[#c18df0]' }}">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span></div><div class="mt-3 flex items-baseline gap-1.5"><p class="text-[22px] font-semibold tracking-tight">{{ \App\Support\MoneyFormatter::format($value) }}</p><span class="text-[10px] text-[#776a8e]">USDT</span></div><svg viewBox="0 0 160 38" preserveAspectRatio="none" class="mt-3 h-9 w-full"><polyline points="{{ $points }}" fill="none" stroke="{{ $index % 2 ? '#70d7e8' : '#b879ec' }}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div>
            </article>
        @endforeach
    </section>

    <section class="mt-4 rounded-[20px] border border-white/[.07] bg-[#352e43] p-4"><div class="flex items-center justify-between"><div><h3 class="font-semibold">Комиссии</h3><p class="text-xs text-[#9588aa]">Доход и внешние расходы не смешиваются</p></div></div><div class="mt-4 grid gap-3 md:grid-cols-3">@foreach(['today'=>'Сегодня','month'=>'Этот месяц','all'=>'Всё время'] as $period=>$label)<div class="rounded-xl bg-white/[.025] p-3"><p class="text-xs text-[#9588aa]">{{ $label }}</p>@foreach([['platform_revenue','Доход платформы','text-cyan-200'],['provider_cost','Расход провайдера','text-amber-200'],['unclassified','Не классифицировано','text-[#aaa0b3]']] as [$key,$name,$color])<div class="mt-2 flex items-start justify-between gap-2 text-xs"><span class="text-[#8f829f]">{{ $name }}</span><div class="text-right {{ $color }}">@forelse($feeSummary[$period][$key] as $currency=>$amount)<p>{{ \App\Support\MoneyFormatter::format($amount) }} {{ $currency }}</p>@empty<p>0.00 USDT</p>@endforelse</div></div>@endforeach</div>@endforeach</div></section>

    <section class="mt-4 grid gap-4 xl:grid-cols-[1.4fr_.6fr]">
        <article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><div><h3 class="font-semibold">Финансовые операции</h3><p class="mt-1 text-xs text-[#9588aa]">Сегодня и текущий месяц</p></div><div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Пополнено сегодня',$financialOperations['todayDeposited'],'USDT'],['Выведено сегодня',$financialOperations['todayWithdrawn'],'USDT'],['Комиссии платформы',$financialOperations['todayFees'],'USDT'],['Ожидают обработки',$financialOperations['waiting'],null],['Пополнено за месяц',$financialOperations['monthDeposited'],'USDT'],['Выведено за месяц',$financialOperations['monthWithdrawn'],'USDT'],['Доход платформы за месяц',$financialOperations['monthRevenue'],'USDT']] as [$label,$value,$currency])<div class="rounded-xl bg-white/[.025] p-3"><p class="text-[10px] text-[#9588aa]">{{ $label }}</p><p class="mt-2 font-semibold">{{ $currency?\App\Support\MoneyFormatter::format($value):$value }} @if($currency)<span class="text-[9px] font-normal text-[#776a8e]">{{ $currency }}</span>@endif</p></div>@endforeach</div></article>
        <article class="rounded-[20px] border border-white/[.07] bg-[#352e43] p-4 sm:p-5"><div><h3 class="font-semibold">Риск-индикаторы</h3><p class="mt-1 text-xs text-[#9588aa]">Информационные сигналы без блокировок</p></div><div class="mt-4 space-y-2">@forelse($riskIndicators as $risk)<a href="{{ $risk['route'] }}" class="block rounded-xl border border-amber-300/10 bg-amber-300/[.035] p-3"><p class="text-xs font-medium text-amber-100">{{ $risk['label'] }}</p><p class="mt-1 text-[10px] text-[#998ca7]">{{ $risk['detail'] }}</p></a>@empty<p class="rounded-xl bg-white/[.025] p-4 text-xs text-[#9080ba]">Рисков не обнаружено.</p>@endforelse</div></article>
    </section>

    <section class="mt-4 grid gap-4 xl:grid-cols-12">
        <article class="rounded-[24px] border border-white/[.07] bg-[#342c43] p-5 sm:p-6 xl:col-span-7">
            <div class="flex flex-wrap items-start justify-between gap-3"><div><h3 class="text-base font-semibold">Обзор системы</h3><div class="mt-2 flex flex-wrap gap-3 text-[10px] text-[#9487a9]"><span class="flex items-center gap-1.5"><i class="size-1.5 rounded-full bg-[#b879ec]"></i> Капитал</span><span class="flex items-center gap-1.5"><i class="size-1.5 rounded-full bg-cyan-300"></i> Начисления</span><span class="flex items-center gap-1.5"><i class="size-1.5 rounded-full bg-[#fa829b]"></i> Выплаты</span></div></div><span class="rounded-xl border border-white/[.07] bg-[#292236] px-3 py-2 text-[11px] text-[#a89bb8]">30 дней</span></div>
            <div class="relative mt-4 h-[225px] w-full overflow-hidden"><div class="absolute inset-2 grid grid-rows-4"><i class="border-t border-white/[.05]"></i><i class="border-t border-white/[.05]"></i><i class="border-t border-white/[.05]"></i><i class="border-t border-white/[.05]"></i></div><svg viewBox="0 0 760 210" preserveAspectRatio="none" class="relative h-full w-full" aria-label="Обзор показателей за 30 дней"><polyline points="{{ $capitalPoints }}" fill="none" stroke="#b879ec" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><polyline points="{{ $accrualPoints }}" fill="none" stroke="#70d7e8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><polyline points="{{ $dividendPoints }}" fill="none" stroke="#fa829b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></div>
            <div class="mt-1 flex justify-between text-[9px] text-[#746781]">@foreach($chartLabels as $date)<span>{{ $date->format('d.m') }}</span>@endforeach</div>
            <div class="mt-5 grid grid-cols-2 gap-3 border-t border-white/[.06] pt-4 sm:grid-cols-4"><div><p class="text-[10px] text-[#847795]">Всего инвесторов</p><p class="mt-1 font-semibold">{{ $summary['investors'] }}</p></div><div><p class="text-[10px] text-[#847795]">Выплачено дивидендов</p><p class="mt-1 font-semibold">{{ \App\Support\MoneyFormatter::format($summary['paidDividends']) }}</p></div><div><p class="text-[10px] text-[#847795]">Выводы в работе</p><p class="mt-1 font-semibold">{{ $summary['withdrawalCount'] }}</p></div><div><p class="text-[10px] text-[#847795]">Пополнения в работе</p><p class="mt-1 font-semibold">{{ $summary['depositCount'] }}</p></div></div>
        </article>

        <article class="rounded-[24px] border border-white/[.07] bg-[#342c43] p-5 xl:col-span-2">
            <div><h3 class="text-base font-semibold">Быстрые действия</h3><p class="mt-1 text-xs text-[#8d80a1]">Рабочие разделы</p></div>
            <div class="mt-5 space-y-2.5">
                <a href="{{ route('admin.investors.create') }}" wire:navigate class="group flex items-center gap-3 rounded-2xl border border-[#b675e8]/20 bg-[#a866dc]/10 p-3 transition hover:bg-[#a866dc]/20"><span class="flex size-9 items-center justify-center rounded-xl bg-[#a968dc] text-lg">+</span><span><b class="block text-xs font-medium">Добавить инвестора</b><small class="text-[10px] text-[#8e80a2]">Новый профиль</small></span></a>
                <a href="{{ route('admin.deposits.index') }}" wire:navigate class="group flex items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.025] p-3 transition hover:border-cyan-300/20"><span class="flex size-9 items-center justify-center rounded-xl bg-cyan-300/10 text-cyan-300">↓</span><span><b class="block text-xs font-medium">Внести средства</b><small class="text-[10px] text-[#8e80a2]">Пополнения</small></span></a>
                <a href="{{ route('admin.withdrawals.index') }}" wire:navigate class="group flex items-center gap-3 rounded-2xl border border-white/[.06] bg-white/[.025] p-3 transition hover:border-[#fa829b]/20"><span class="flex size-9 items-center justify-center rounded-xl bg-[#fa829b]/10 text-[#fa9bae]">↑</span><span><b class="block text-xs font-medium">Открыть выводы</b><small class="text-[10px] text-[#8e80a2]">Заявки</small></span></a>
            </div>
        </article>

        <article class="rounded-[24px] border border-white/[.07] bg-[#342c43] p-5 xl:col-span-3">
            <div class="flex items-start justify-between"><div><h3 class="text-base font-semibold">Требуют внимания</h3><p class="mt-1 text-xs text-[#8d80a1]">Очередь операций</p></div><span class="rounded-lg bg-[#fa829b]/10 px-2 py-1 text-[10px] text-[#fa9bae]">{{ $attention->count() }}</span></div>
            <div class="mt-4 space-y-1.5">@forelse($attention as $item)<a href="{{ $item['route'] }}" wire:navigate class="flex items-center gap-3 rounded-xl p-2.5 transition hover:bg-white/[.035]"><span class="flex size-8 shrink-0 items-center justify-center rounded-xl {{ $item['kind']==='Пополнение' ? 'bg-cyan-300/10 text-cyan-300' : 'bg-[#b879ec]/10 text-[#c999ef]' }}">{{ $item['kind']==='Пополнение' ? '↓' : '↑' }}</span><span class="min-w-0 flex-1"><b class="block truncate text-[11px] font-medium">{{ $item['investor'] }}</b><small class="block truncate text-[9px] text-[#81748f]">{{ $item['kind'] }} · {{ $item['date']->format('d.m H:i') }}</small></span><span class="text-right"><b class="block whitespace-nowrap text-[10px] font-medium">{{ \App\Support\MoneyFormatter::format($item['amount']) }}</b><small class="text-[9px] text-amber-300">{{ $item['status'] }}</small></span></a>@empty<div class="rounded-2xl border border-dashed border-white/[.07] px-4 py-10 text-center text-xs text-[#7f718f]">Нет операций, требующих внимания</div>@endforelse</div>
            <a href="{{ route('admin.withdrawals.index') }}" wire:navigate class="mt-4 block border-t border-white/[.06] pt-3 text-center text-[11px] text-[#c08cee] hover:text-white">Смотреть все</a>
        </article>
    </section>
</div>
