<div class="mx-auto max-w-[1800px]" data-admin-wallets>
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><h2 class="text-2xl font-semibold tracking-tight">Кошельки</h2><p class="mt-1 text-xs text-[#9080ba]">Управление кошельками инвесторов и адресами пополнения</p></div>
        @if($activeTab === 'addresses')<button type="button" wire:click="openAddressModal" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#727ce7] px-4 py-2.5 text-xs font-semibold hover:brightness-110">+ Добавить адрес пополнения</button>@endif
    </header>

    @if(session('success'))<div class="mt-4 rounded-2xl border border-cyan-300/20 bg-cyan-300/[.07] px-4 py-3 text-xs text-cyan-200">{{ session('success') }}</div>@endif

    <nav class="mt-5 flex w-fit max-w-full gap-1 overflow-x-auto rounded-2xl border border-white/[.06] bg-[#332c42] p-1.5">
        <button wire:click="selectTab('wallets')" class="whitespace-nowrap cursor-pointer rounded-xl px-4 py-2 text-xs {{ $activeTab==='wallets' ? 'bg-[#ac6aec]/20 text-white' : 'text-[#9080ba] hover:bg-white/[.04]' }}">Кошельки инвесторов</button>
        <button wire:click="selectTab('addresses')" class="whitespace-nowrap cursor-pointer rounded-xl px-4 py-2 text-xs {{ $activeTab==='addresses' ? 'bg-[#ac6aec]/20 text-white' : 'text-[#9080ba] hover:bg-white/[.04]' }}">Адреса пополнения</button>
    </nav>

    @if($activeTab === 'wallets')
        <section class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
            @foreach([['Всего кошельков',$walletKpis['total']],['На проверке',$walletKpis['pending']],['Одобрено',$walletKpis['approved']],['Архивировано',$walletKpis['archived']]] as [$label,$value])<article class="rounded-[18px] border border-white/[.065] bg-[#3c354a] p-4"><p class="text-[10px] text-[#9080ba]">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">{{ $value }}</p></article>@endforeach
        </section>
        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#3c354a]">
            <div class="grid gap-2 border-b border-white/[.06] bg-[#332c42] p-4 md:grid-cols-2 xl:grid-cols-5">
                <input wire:model.live.debounce.300ms="walletSearch" placeholder="Имя, email, код или адрес…" class="h-10 rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs outline-none focus:border-cyan-300/40">
                <select wire:model.live="walletStatus" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все статусы</option><option value="pending">На проверке</option><option value="approved">Одобрено</option><option value="blocked">Заблокировано</option><option value="archived">Архивировано</option></select>
                <select wire:model.live="walletNetwork" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все сети</option>@foreach($walletNetworks as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select>
                <select wire:model.live="walletCurrency" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все валюты</option>@foreach($walletCurrencies as $value)<option value="{{ $value }}">{{ $value }}</option>@endforeach</select>
                <select wire:model.live="walletInvestor" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все инвесторы</option>@foreach($investors as $item)<option value="{{ $item->id }}">{{ $item->user->name }}</option>@endforeach</select>
            </div>
            <div class="hidden grid-cols-[minmax(130px,1.2fr)_minmax(110px,.9fr)_70px_80px_minmax(130px,1fr)_minmax(120px,auto)_112px_36px] items-center gap-3 border-b border-white/[.06] bg-[#332c42] px-5 py-3 text-[9px] uppercase tracking-wide text-[#817590] lg:grid"><span>Инвестор</span><span>Название</span><span>Валюта</span><span>Сеть</span><span>Адрес</span><span>Статус</span><span>Дата добавления</span><span></span></div>
            <div class="divide-y divide-white/[.05]">
                @forelse($wallets as $wallet) @php $label=\App\Support\WalletPresentation::walletStatus($wallet->status); $badge=match($wallet->status){'pending'=>'bg-amber-300/10 text-amber-200','approved'=>'bg-cyan-300/10 text-cyan-200','blocked'=>'bg-red-400/10 text-red-300',default=>'bg-white/[.06] text-[#a99db6]'}; @endphp
                    <article x-data="{ expanded:false }" class="bg-[#3a3348]/45 transition hover:bg-white/[.04]">
                        <button type="button" @click="expanded=!expanded" x-bind:aria-expanded="expanded" aria-controls="wallet-details-{{ $wallet->id }}" class="w-full cursor-pointer px-4 py-4 text-left outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-300/40 lg:px-5">
                            <span class="grid grid-cols-[1fr_auto] gap-3 lg:hidden"><span><b class="block truncate text-xs font-medium">{{ $wallet->investor->user->name }}</b><small class="mt-1 block truncate text-[9px] text-[#817590]">{{ $wallet->label ?: 'Без названия' }}</small></span><span class="justify-self-end"><span class="rounded-full px-2 py-1 text-[9px] {{ $badge }}">{{ $label }}</span></span><span class="text-[10px] text-white">{{ $wallet->currency }} · {{ $wallet->network }}</span><span class="font-mono text-xs text-cyan-100" title="{{ $wallet->address }}">{{ \App\Support\WalletPresentation::shortAddress($wallet->address) }}</span><span class="col-span-2 justify-self-end text-[10px] text-[#9080ba]">Подробнее <span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-block transition">⌄</span></span></span>
                            <span class="hidden grid-cols-[minmax(130px,1.2fr)_minmax(110px,.9fr)_70px_80px_minmax(130px,1fr)_minmax(120px,auto)_112px_36px] items-center gap-3 lg:grid"><span class="truncate text-xs font-medium">{{ $wallet->investor->user->name }}</span><span class="truncate text-xs text-[#b8adbf]">{{ $wallet->label ?: '—' }}</span><span class="text-xs">{{ $wallet->currency }}</span><span class="text-xs">{{ $wallet->network }}</span><span class="truncate font-mono text-xs text-cyan-100" title="{{ $wallet->address }}">{{ \App\Support\WalletPresentation::shortAddress($wallet->address) }}</span><span class="min-w-[120px]"><span class="inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[9px] {{ $badge }}">{{ $label }}</span></span><time class="whitespace-nowrap text-[10px] text-[#9487a1]" datetime="{{ $wallet->created_at->toDateString() }}">{{ $wallet->created_at->format('d.m.Y') }}</time><span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-flex size-8 cursor-pointer items-center justify-center justify-self-end text-[#9080ba] transition">⌄</span></span>
                        </button>
                        <div id="wallet-details-{{ $wallet->id }}" x-show="expanded" x-cloak class="border-t border-white/[.05] bg-[#332c42]/70 p-4 lg:p-5">
                            <dl class="grid gap-3 text-[10px] sm:grid-cols-2 xl:grid-cols-4"><div><dt class="text-[#817590]">Инвестор / Email / Код</dt><dd class="mt-1 text-white">{{ $wallet->investor->user->name }} · {{ $wallet->investor->user->email }} · {{ $wallet->investor->code ?: '—' }}</dd></div><div><dt class="text-[#817590]">Кошелёк</dt><dd class="mt-1 text-white">{{ $wallet->label ?: 'Без названия' }} · {{ $wallet->currency }} · {{ $wallet->network }}</dd></div><div><dt class="text-[#817590]">Статус / Дата</dt><dd class="mt-1 text-white">{{ $label }} · {{ $wallet->created_at->format('d.m.Y H:i') }}</dd></div><div><dt class="text-[#817590]">Кем и когда одобрен</dt><dd class="mt-1 text-white">{{ $wallet->approvedBy?->name ?: '—' }} · {{ $wallet->approved_at?->format('d.m.Y H:i') ?: '—' }}</dd></div></dl>
                            <div class="mt-4 flex flex-col gap-2 rounded-xl bg-[#2f293e] p-3 sm:flex-row sm:items-center"><code class="min-w-0 flex-1 break-all text-xs text-cyan-100">{{ $wallet->address }}</code><button type="button" onclick="navigator.clipboard.writeText(@js($wallet->address)); this.textContent='Скопировано'" class="cursor-pointer rounded-lg border border-cyan-300/20 px-3 py-2 text-[10px] text-cyan-200">Копировать</button></div>
                            <div class="mt-3 flex flex-wrap gap-2">@if($wallet->status==='pending')<button wire:click="confirm('approve-wallet',{{ $wallet->id }})" class="cursor-pointer rounded-lg bg-cyan-300/15 px-3 py-2 text-[10px] text-cyan-200">Одобрить</button>@endif @if(in_array($wallet->status,['pending','approved']))<button wire:click="confirm('block-wallet',{{ $wallet->id }})" class="cursor-pointer rounded-lg border border-red-300/15 px-3 py-2 text-[10px] text-red-300">Заблокировать</button>@endif @if($wallet->status!=='archived')<button wire:click="confirm('archive-wallet',{{ $wallet->id }})" class="cursor-pointer rounded-lg border border-white/[.09] px-3 py-2 text-[10px] text-[#b6a9c1]">Архивировать</button>@endif</div>
                        </div>
                    </article>
                @empty<div class="px-5 py-12 text-center text-xs text-[#9080ba]">Кошельки не найдены.</div>@endforelse
            </div>
            @if($wallets->hasPages())<div class="border-t border-white/[.06] p-4">{{ $wallets->links() }}</div>@endif
        </section>
    @else
        <section class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Всего адресов',$addressKpis['total']],['Активных',$addressKpis['active']],['Назначено инвесторам',$addressKpis['assigned']],['Архивировано',$addressKpis['archived']]] as [$label,$value])<article class="rounded-[18px] border border-white/[.065] bg-[#3c354a] p-4"><p class="text-[10px] text-[#9080ba]">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">{{ $value }}</p></article>@endforeach</section>
        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#3c354a]">
            <div class="grid gap-2 border-b border-white/[.06] bg-[#332c42] p-4 md:grid-cols-2 xl:grid-cols-5"><input wire:model.live.debounce.300ms="addressSearch" placeholder="Инвестор, адрес или provider…" class="h-10 rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><select wire:model.live="addressStatus" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все статусы</option><option value="active">Активен</option><option value="inactive">Неактивен</option><option value="archived">Архивирован</option></select><select wire:model.live="addressNetwork" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все сети</option>@foreach($addressNetworks as $value)<option>{{ $value }}</option>@endforeach</select><select wire:model.live="addressCurrency" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все валюты</option>@foreach($addressCurrencies as $value)<option>{{ $value }}</option>@endforeach</select><select wire:model.live="addressProvider" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все providers</option>@foreach($providers as $value)<option>{{ $value }}</option>@endforeach</select></div>
            <div class="hidden grid-cols-[minmax(130px,1.1fr)_70px_80px_minmax(130px,1fr)_minmax(90px,.7fr)_minmax(120px,auto)_112px_36px] items-center gap-3 border-b border-white/[.06] bg-[#332c42] px-5 py-3 text-[9px] uppercase tracking-wide text-[#817590] lg:grid"><span>Инвестор</span><span>Валюта</span><span>Сеть</span><span>Адрес</span><span>Provider</span><span>Статус</span><span>Дата создания</span><span></span></div>
            <div class="divide-y divide-white/[.05]">@forelse($addresses as $address) @php $label=\App\Support\WalletPresentation::addressStatus($address); $badge=$address->archived_at?'bg-white/[.06] text-[#a99db6]':($address->is_active?'bg-emerald-400/10 text-emerald-300':'bg-amber-300/10 text-amber-200'); @endphp
                <article x-data="{ expanded:false }" class="bg-[#3a3348]/45 hover:bg-white/[.04]"><button type="button" @click="expanded=!expanded" x-bind:aria-expanded="expanded" aria-controls="address-details-{{ $address->id }}" class="w-full cursor-pointer px-4 py-4 text-left outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-300/40 lg:px-5"><span class="grid grid-cols-[1fr_auto] gap-3 lg:hidden"><span class="truncate text-xs font-medium">{{ $address->investor?->user?->name ?: 'Не назначен' }}</span><span class="justify-self-end"><span class="rounded-full px-2 py-1 text-[9px] {{ $badge }}">{{ $label }}</span></span><span class="text-[10px]">{{ $address->currency }} · {{ $address->network }}</span><span class="font-mono text-xs text-cyan-100" title="{{ $address->address }}">{{ \App\Support\WalletPresentation::shortAddress($address->address) }}</span><span class="text-[10px] text-[#a99db6]">Provider: {{ $address->provider ?: '—' }}</span><span class="justify-self-end text-[10px] text-[#9080ba]">Подробнее <span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-block transition">⌄</span></span></span><span class="hidden grid-cols-[minmax(130px,1.1fr)_70px_80px_minmax(130px,1fr)_minmax(90px,.7fr)_minmax(120px,auto)_112px_36px] items-center gap-3 lg:grid"><span class="truncate text-xs font-medium">{{ $address->investor?->user?->name ?: 'Не назначен' }}</span><span class="text-xs">{{ $address->currency }}</span><span class="text-xs">{{ $address->network }}</span><span class="truncate font-mono text-xs text-cyan-100" title="{{ $address->address }}">{{ \App\Support\WalletPresentation::shortAddress($address->address) }}</span><span class="truncate text-[10px] text-[#a99db6]">{{ $address->provider ?: '—' }}</span><span class="min-w-[120px]"><span class="inline-flex whitespace-nowrap rounded-full px-2 py-1 text-[9px] {{ $badge }}">{{ $label }}</span></span><time class="whitespace-nowrap text-[10px] text-[#9487a1]" datetime="{{ $address->created_at->toDateString() }}">{{ $address->created_at->format('d.m.Y') }}</time><span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-flex size-8 cursor-pointer items-center justify-center justify-self-end text-[#9080ba] transition">⌄</span></span></button>
                    <div id="address-details-{{ $address->id }}" x-show="expanded" x-cloak class="border-t border-white/[.05] bg-[#332c42]/70 p-4 lg:p-5"><dl class="grid gap-3 text-[10px] sm:grid-cols-2 xl:grid-cols-4"><div><dt class="text-[#817590]">Инвестор</dt><dd class="mt-1 text-white">{{ $address->investor?->user?->name ?: 'Не назначен' }} · {{ $address->investor?->code ?: '—' }}</dd></div><div><dt class="text-[#817590]">Валюта / Сеть / Provider</dt><dd class="mt-1 text-white">{{ $address->currency }} · {{ $address->network }} · {{ $address->provider ?: '—' }}</dd></div><div><dt class="text-[#817590]">Кем создан / Дата</dt><dd class="mt-1 text-white">{{ $address->createdBy?->name ?: 'Система' }} · {{ $address->created_at->format('d.m.Y H:i') }}</dd></div><div><dt class="text-[#817590]">Связанные заявки</dt><dd class="mt-1 text-white">{{ $address->deposit_requests_count }}</dd></div></dl><div class="mt-4 flex flex-col gap-2 rounded-xl bg-[#2f293e] p-3 sm:flex-row sm:items-center"><code class="min-w-0 flex-1 break-all text-xs text-cyan-100">{{ $address->address }}</code><button type="button" onclick="navigator.clipboard.writeText(@js($address->address)); this.textContent='Скопировано'" class="cursor-pointer rounded-lg border border-cyan-300/20 px-3 py-2 text-[10px] text-cyan-200">Копировать</button></div><div class="mt-3 flex gap-2">@if(!$address->investor_id && $address->is_active && !$address->archived_at)<button wire:click="openAssign({{ $address->id }})" class="cursor-pointer rounded-lg bg-cyan-300/15 px-3 py-2 text-[10px] text-cyan-200">Назначить инвестору</button>@endif @if(!$address->archived_at)<button wire:click="confirm('archive-address',{{ $address->id }})" class="cursor-pointer rounded-lg border border-white/[.09] px-3 py-2 text-[10px] text-[#b6a9c1]">Архивировать</button>@endif</div></div>
                </article>@empty<div class="px-5 py-12 text-center text-xs text-[#9080ba]">Адреса пополнения не найдены.</div>@endforelse</div>@if($addresses->hasPages())<div class="border-t border-white/[.06] p-4">{{ $addresses->links() }}</div>@endif
        </section>
    @endif

    @if($showAddressModal)<div class="fixed inset-0 z-50 flex items-center justify-center p-4"><button wire:click="closeAddressModal" class="absolute inset-0 cursor-pointer bg-[#171020]/80 backdrop-blur-sm"></button><form wire:submit="createAddress" role="dialog" aria-modal="true" class="relative w-full max-w-xl overflow-hidden rounded-[18px] border border-white/[.1] bg-[#3c354a]"><header class="border-b border-white/[.07] bg-[#332c42] px-6 py-4"><h3 class="font-semibold">Добавить адрес пополнения</h3></header><div class="grid gap-4 p-6 sm:grid-cols-2">@foreach([['newInvestorId','Инвестор','select'],['newCurrency','Валюта','text'],['newNetwork','Сеть','text'],['newAddress','Адрес','text'],['newProvider','Provider','text'],['newLabel','Название','text']] as [$model,$label,$type])<label class="{{ $model==='newAddress'?'sm:col-span-2':'' }}"><span class="text-[10px] text-[#a99db6]">{{ $label }}</span>@if($type==='select')<select wire:model="{{ $model }}" class="mt-2 h-11 w-full cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Не назначать</option>@foreach($investors as $item)<option value="{{ $item->id }}">{{ $item->user->name }} · {{ $item->code }}</option>@endforeach</select>@else<input wire:model="{{ $model }}" class="mt-2 h-11 w-full rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs">@endif @error($model)<small class="mt-1 block text-red-300">{{ $message }}</small>@enderror</label>@endforeach</div><footer class="flex justify-end gap-2 border-t border-white/[.07] px-6 py-4"><button type="button" wire:click="closeAddressModal" class="cursor-pointer rounded-xl border border-white/[.09] px-4 py-2 text-xs">Отмена</button><button class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#727ce7] px-4 py-2 text-xs font-semibold">Добавить</button></footer></form></div>@endif
    @if($showAssignModal)<div class="fixed inset-0 z-50 flex items-center justify-center p-4"><button wire:click="$set('showAssignModal',false)" class="absolute inset-0 cursor-pointer bg-[#171020]/80"></button><form wire:submit="assignAddress" role="dialog" class="relative w-full max-w-md overflow-hidden rounded-[18px] border border-white/[.1] bg-[#3c354a] p-6"><h3 class="font-semibold">Назначить адрес инвестору</h3><select wire:model="assignInvestorId" class="mt-4 h-11 w-full cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Выберите инвестора</option>@foreach($investors as $item)<option value="{{ $item->id }}">{{ $item->user->name }} · {{ $item->code }}</option>@endforeach</select>@error('assignInvestorId')<small class="mt-2 block text-red-300">{{ $message }}</small>@enderror<div class="mt-5 flex justify-end gap-2"><button type="button" wire:click="$set('showAssignModal',false)" class="cursor-pointer rounded-xl border border-white/[.09] px-4 py-2 text-xs">Отмена</button><button class="cursor-pointer rounded-xl bg-cyan-300/15 px-4 py-2 text-xs text-cyan-200">Назначить</button></div></form></div>@endif
    @if($showConfirmModal)<div class="fixed inset-0 z-50 flex items-center justify-center p-4"><button wire:click="closeConfirm" class="absolute inset-0 cursor-pointer bg-[#171020]/80"></button><form wire:submit="executeConfirmed" role="dialog" aria-modal="true" class="relative w-full max-w-md overflow-hidden rounded-[18px] border border-white/[.1] bg-[#3c354a] p-6"><h3 class="text-base font-semibold">{{ $confirmAction==='approve-wallet'?'Одобрить кошелёк?':($confirmAction==='archive-address'?'Архивировать адрес пополнения?':'Подтвердить действие?') }}</h3>@if($confirmationModel instanceof \App\Models\InvestorWallet)<div class="mt-4 rounded-xl bg-[#2f293e] p-4 text-xs"><p>{{ $confirmationModel->investor->user->name }}</p><p class="mt-2 text-[#a99db6]">{{ $confirmationModel->network }}</p><code class="mt-2 block break-all text-cyan-100">{{ $confirmationModel->address }}</code></div>@else<p class="mt-3 text-xs leading-5 text-[#a99db6]">Новые заявки больше не смогут использовать этот адрес. Старые заявки сохранят snapshot.</p>@endif @error('confirmation')<p class="mt-3 text-xs text-red-300">{{ $message }}</p>@enderror<div class="mt-5 flex justify-end gap-2"><button type="button" wire:click="closeConfirm" class="cursor-pointer rounded-xl border border-white/[.09] px-4 py-2 text-xs">Отмена</button><button class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#727ce7] px-4 py-2 text-xs font-semibold">Подтвердить</button></div></form></div>@endif
</div>
