<div class="mx-auto max-w-[1700px]" style="--program-grid: minmax(160px,1.4fr) minmax(170px,1.25fr) minmax(120px,.9fr) minmax(125px,.95fr) minmax(95px,.7fr) minmax(70px,.55fr) minmax(100px,.7fr) minmax(130px,1fr) minmax(180px,1.15fr)" x-data="{form:false,version:false}" x-on:open-program-form.window="form=true" x-on:close-program-form.window="form=false" x-on:open-version-form.window="version=true" x-on:close-version-form.window="version=false">
    <div class="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <div><h2 class="text-2xl font-semibold">Инвестиционные программы</h2><p class="mt-1 text-xs text-[#9080ba]">Продукты, диапазоны и версии финансовых условий</p></div>
        <button wire:click="create" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#686ee8] px-4 py-2.5 text-sm font-semibold">+ Создать программу</button>
    </div>
    <div class="overflow-hidden rounded-[18px] border border-white/[.08] bg-[#3c354a]">
        <div class="hidden gap-3 bg-[#332c42] px-4 py-3 text-[10px] uppercase tracking-wide text-[#998cad] min-[1380px]:grid min-[1380px]:grid-cols-[var(--program-grid)]"><span>Программа</span><span>Диапазон суммы</span><span>Доходность в месяц</span><span>Доступность капитала</span><span>Статус</span><span>Инвесторы</span><span>Активные инвестиции</span><span>Капитал программы</span><span>Действия</span></div>
        @forelse($programs as $program)
            @php($version=$program->versions->first())
            <article class="grid gap-3 border-t border-white/[.06] px-4 py-4 hover:bg-white/[.035] min-[1380px]:grid-cols-[var(--program-grid)] min-[1380px]:items-center">
                <div><b>{{ $program->name }}</b><p class="text-xs text-[#8f82a1]">{{ $program->description }}</p></div>
                <p class="text-sm">{{ \App\Support\MoneyFormatter::format($program->min_amount) }} — {{ $program->max_amount?\App\Support\MoneyFormatter::format($program->max_amount):'∞' }} {{ $program->currency }}</p>
                <p>{{ $version?\App\Support\InvestmentTermPresentation::rate((string)$version->monthly_rate):'—' }}</p><p>{{ $version?->lock_months??'—' }} мес.</p>
                <span class="w-fit rounded-full bg-purple-300/10 px-2 py-1 text-xs text-purple-100">{{ ['draft'=>'Черновик','active'=>'Активна','paused'=>'Приостановлена','archived'=>'Архив'][$program->status] }}</span>
                <p>{{ $program->lots->pluck('investmentAccount.investor_id')->unique()->count() }}</p>
                <p>{{ $program->lots_count }}</p>
                <p>{{ \App\Support\MoneyFormatter::format($program->lots->reduce(fn($sum,$lot)=>app(\App\Services\AccrualCalculator::class)->add($sum,(string)$lot->remaining_amount),'0')) }} {{ $program->currency }}</p>
                <div class="flex gap-2"><button wire:click="edit({{ $program->id }})" class="cursor-pointer text-xs text-cyan-200">Изменить</button><button wire:click="addVersion({{ $program->id }})" class="cursor-pointer text-xs text-purple-200">Версия</button>@if($program->status!=='archived')<button wire:click="archive({{ $program->id }})" class="cursor-pointer text-xs text-rose-200">Архив</button>@endif</div>
                <div class="rounded-xl bg-white/[.025] p-3 min-[1380px]:col-span-9"><p class="text-xs text-[#9486a5]">История условий</p><div class="mt-2 flex flex-wrap gap-2">@foreach($program->versions as $i=>$item)<span class="rounded-lg border border-white/[.06] px-2 py-1 text-[10px]">v{{ $program->versions->count()-$i }} · {{ \App\Support\InvestmentTermPresentation::rate((string)$item->monthly_rate) }} · {{ $item->lock_months }} мес. · {{ $item->valid_from->format('d.m.Y') }} — {{ $item->valid_to?->format('d.m.Y')??'сейчас' }}</span>@endforeach</div></div>
            </article>
        @empty <div class="p-10 text-center text-[#9080ba]">Программы ещё не созданы.</div> @endforelse
    </div><div class="mt-4">{{ $programs->links() }}</div>
    <div x-show="form" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form wire:submit="save" class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-[18px] border border-white/10 bg-[#3c354a] p-6"><div class="flex justify-between"><h3 class="text-lg font-semibold">{{ $editingId?'Изменить программу':'Новая программа' }}</h3><button type="button" x-on:click="form=false" class="cursor-pointer">✕</button></div><div class="mt-5 grid gap-4 sm:grid-cols-2">@foreach([['name','Название'],['currency','Валюта'],['minAmount','Минимум'],['maxAmount','Максимум']] as [$field,$label])<label class="text-xs text-[#a99db4]">{{ $label }}<input wire:model="{{ $field }}" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-3 text-white"></label>@endforeach<label class="sm:col-span-2 text-xs text-[#a99db4]">Описание<textarea wire:model="description" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-3"></textarea></label><label class="text-xs">Статус<select wire:model="status" class="mt-1 w-full rounded-xl bg-[#2f293e] p-3"><option value="draft">Черновик</option><option value="active">Активна</option><option value="paused">Приостановлена</option><option value="archived">Архив</option></select></label><label class="flex items-center gap-2 pt-6 text-sm"><input type="checkbox" wire:model="partialWithdrawal"> Частичный вывод</label><label class="text-xs">Доходность в месяц (%)<input wire:model="monthlyRate" class="mt-1 w-full rounded-xl bg-[#2f293e] p-3"></label><label class="text-xs">Капитал доступен к выводу через (месяцев)<input wire:model="lockMonths" class="mt-1 w-full rounded-xl bg-[#2f293e] p-3"></label><label class="text-xs">Дата начала действия<input wire:model="validFrom" type="date" class="mt-1 w-full rounded-xl bg-[#2f293e] p-3"></label>@if($editingId)<p class="self-end rounded-xl border border-amber-300/10 bg-amber-300/[.05] p-3 text-xs text-amber-100">Изменение применяется только к новым инвестициям. Существующие инвестиции сохраняют старые условия.</p>@endif</div>@if($errors->any())<div class="mt-4 rounded-xl bg-rose-400/10 p-3 text-xs text-rose-200">{{ $errors->first() }}</div>@endif<div class="mt-5 flex justify-end"><button class="cursor-pointer rounded-xl bg-purple-500 px-5 py-2.5">Сохранить</button></div></form></div>
    <div x-show="version" x-cloak class="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form wire:submit="saveVersion" class="w-full max-w-lg rounded-[18px] border border-white/10 bg-[#3c354a] p-6"><div class="flex justify-between"><h3 class="font-semibold">Новая версия условий</h3><button type="button" x-on:click="version=false">✕</button></div><div class="mt-4 space-y-3"><input wire:model="monthlyRate" placeholder="Ставка, %" class="w-full rounded-xl bg-[#2f293e] p-3"><input wire:model="lockMonths" placeholder="Срок, месяцев" class="w-full rounded-xl bg-[#2f293e] p-3"><input wire:model="validFrom" type="date" class="w-full rounded-xl bg-[#2f293e] p-3"></div><button class="mt-4 w-full rounded-xl bg-purple-500 p-3">Создать версию</button></form></div>
</div>
