@php use App\Support\SupportPresentation as SP; @endphp
<div class="space-y-5">
    <div><p class="text-sm font-medium text-purple-300">Операционный центр</p><h2 class="mt-1 text-2xl font-semibold">Financial Operations Center</h2><p class="mt-1 text-sm text-[#9080ba]">Финансовые заявки, проверки и обращения инвесторов в единой очереди</p></div>
    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Требуют действия','attention'],['На проверке','review'],['Готово','ready'],['Обращения','support']] as [$label,$key])<div class="rounded-[18px] border border-white/[.06] bg-[#3c354a] p-4"><p class="text-xs text-[#9080ba]">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">{{ $kpis[$key] }}</p></div>@endforeach</div>
    <nav class="flex gap-1 overflow-x-auto rounded-xl bg-[#2d263a] p-1">@foreach(['action'=>'Требуют действия','review'=>'На проверке','ready'=>'Готово','support'=>'Обращения'] as $value=>$label)<button wire:click="$set('tab','{{ $value }}')" class="shrink-0 cursor-pointer rounded-lg px-4 py-2.5 text-sm {{ $tab===$value?'bg-purple-300/15 text-purple-100':'text-[#9080ba] hover:bg-white/[.03]' }}">{{ $label }}</button>@endforeach</nav>
    <div class="flex flex-wrap gap-2"><input wire:model.live.debounce.300ms="search" placeholder="Инвестор, операция или ID" class="min-w-52 flex-1 rounded-xl border border-white/[.07] bg-[#332c42] px-3 py-2.5 text-sm focus:border-cyan-300/30 focus:outline-none"><select wire:model.live="type" class="cursor-pointer rounded-xl border border-white/[.07] bg-[#332c42] px-3 py-2.5 text-sm"><option value="">Все типы</option><option value="withdrawal">Выводы</option><option value="deposit">Пополнения</option><option value="wallet">Кошельки</option><option value="support">Поддержка</option></select><select wire:model.live="sort" class="cursor-pointer rounded-xl border border-white/[.07] bg-[#332c42] px-3 py-2.5 text-sm"><option value="priority">Срочные и старые</option><option value="oldest">Сначала старые</option><option value="newest">Сначала новые</option></select></div>
    <div class="grid gap-4 xl:grid-cols-[minmax(0,1fr)_440px]"><section class="space-y-3">@forelse($items as $item)<x-admin.operation-card :item="$item" />@empty<div class="rounded-[18px] border border-dashed border-white/[.08] bg-[#3c354a]/50 px-6 py-14 text-center text-sm text-[#9080ba]">В этой очереди пока нет элементов.</div>@endforelse</section>
    @if($ticket)<aside class="h-fit rounded-[20px] border border-white/[.08] bg-[#342c43] p-4"><h3 class="font-semibold">Обращение #{{ $ticket->id }}</h3><p>{{ $ticket->subject }}</p><p class="text-xs text-[#9080ba]">{{ $ticket->investor->user->name }} · {{ $ticket->investor->code }}</p><div class="mt-3 flex gap-2"><select wire:model="status" class="rounded-lg bg-[#292235] p-2 text-xs">@foreach(\App\Models\SupportTicket::STATUSES as $v)<option value="{{ $v }}">{{ SP::status($v) }}</option>@endforeach</select><button wire:click="changeStatus" class="cursor-pointer rounded-lg bg-purple-300/10 px-3 text-xs">Изменить</button></div><div class="mt-2 flex gap-2"><select wire:model="assigneeId" class="rounded-lg bg-[#292235] p-2 text-xs"><option value="">Назначить</option>@foreach($admins as $a)<option value="{{ $a->id }}">{{ $a->name }}</option>@endforeach</select><button wire:click="assign" class="cursor-pointer rounded-lg bg-purple-300/10 px-3 text-xs">Назначить</button></div><div class="mt-4 max-h-72 space-y-2 overflow-y-auto">@foreach($ticket->messages as $message)<div class="rounded-xl p-3 text-sm {{ $message->is_internal?'border border-amber-300/20 bg-amber-300/[.06]':'bg-white/[.04]' }}"><p class="text-xs text-[#9080ba]">{{ $message->user->name }} {{ $message->is_internal?'· Внутренняя заметка':'' }}</p><p class="mt-1 whitespace-pre-wrap">{{ $message->message }}</p></div>@endforeach</div><textarea wire:model="replyText" placeholder="Ответ инвестору" class="mt-3 w-full rounded-xl bg-[#292235] p-3 text-sm"></textarea><button wire:click="reply" class="mt-2 cursor-pointer rounded-lg bg-cyan-300/10 px-3 py-2 text-xs text-cyan-100">Отправить ответ</button><textarea wire:model="noteText" placeholder="Внутренняя заметка" class="mt-3 w-full rounded-xl border border-amber-300/15 bg-[#292235] p-3 text-sm"></textarea><button wire:click="note" class="mt-2 cursor-pointer rounded-lg bg-amber-300/10 px-3 py-2 text-xs text-amber-100">Добавить заметку</button></aside>@endif</div>
</div>
