<?php
namespace Tests\Feature;
use App\Livewire\Admin\Withdrawals\Index;use App\Models\{AuditLog,DailyAccrual,InvestmentAccount,InvestmentLot,Investor,User,WithdrawalRequest};use App\Services\WithdrawalVerificationService;use Carbon\Carbon;use Illuminate\Foundation\Testing\RefreshDatabase;use Livewire\Livewire;use Tests\TestCase;
class AdminWithdrawalsTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();Carbon::setTestNow('2026-08-11 12:00:00');}protected function tearDown():void{Carbon::setTestNow();parent::tearDown();}
public function test_status_actions_mobile_and_modal_details():void{[$admin,$investor,$account]=$this->context();foreach(['new','review','approved','paid','cancelled','rejected'] as $status)$this->request($investor,$account,$status);$component=Livewire::actingAs($admin)->test(Index::class)->assertSee('Действие')->assertSee('Рассмотреть')->assertSee('Обработать')->assertSee('Выплатить')->assertSeeHtml('md:hidden');$review=WithdrawalRequest::where('status','review')->first();$component->call('openAction',$review->id)->assertSee('Обработка заявки на вывод')->assertSee('Проверка выплаты')->assertSee('Проверено')->assertSee('Проверить реквизиты')->assertSee($investor->user->name)->assertSee('TFullWalletSnapshot001')->assertSee('100.00 USDT')->assertSee('Комиссия платформы')->assertSee('Инвестор')->assertSee('Одобрить')->assertSee('Отклонить')->assertSee('Отменить')->assertSeeHtml('x-on:keydown.escape.window')->assertSeeHtml('cursor-pointer');}
public function test_transitions_payment_confirmation_deeplink_errors_and_audit():void{[$admin,$investor,$account]=$this->context();$new=$this->request($investor,$account,'new');Livewire::actingAs($admin)->test(Index::class)->call('openAction',$new->id)->call('takeToReview')->assertHasNoErrors();$this->assertSame('review',$new->fresh()->status);$review=$this->request($investor,$account,'review');Livewire::actingAs($admin)->test(Index::class)->call('openAction',$review->id)->call('approve');$this->assertSame('approved',$review->fresh()->status);$reject=$this->request($investor,$account,'review');Livewire::actingAs($admin)->test(Index::class)->call('openAction',$reject->id)->set('rejectionReason','Проверка не пройдена')->call('reject');$this->assertSame('rejected',$reject->fresh()->status);
DailyAccrual::create(['investment_account_id'=>$account->id,'investment_lot_id'=>$this->lot($account)->id,'accrual_date'=>'2026-08-11','principal_amount'=>'1000','monthly_rate'=>'3','days_in_month'=>31,'calculated_amount'=>'200','final_amount'=>'200']);$dividend=$this->request($investor,$account,'approved');$this->complete($dividend,$admin);Livewire::actingAs($admin)->test(Index::class)->call('openAction',$dividend->id)->call('requestPaymentConfirmation')->assertSet('actionStep','confirm')->assertSee('Проверьте сеть и адрес')->set('txid','tx-dividend')->call('confirmPayment')->assertHasNoErrors();$this->assertSame('paid',$dividend->fresh()->status);$this->assertDatabaseHas('dividend_payments',['withdrawal_request_id'=>$dividend->id,'txid'=>'tx-dividend']);
$capital=$this->request($investor,$account,'approved','capital');$lot=$this->lot($account,'2000');$this->complete($capital,$admin);Livewire::actingAs($admin)->test(Index::class)->call('openAction',$capital->id)->call('requestPaymentConfirmation')->set('txid','tx-capital')->call('confirmPayment')->assertHasNoErrors();$this->assertSame('paid',$capital->fresh()->status);$this->assertSame('100.00000000',(string)$capital->capitalWithdrawalAllocations()->sum('amount'));$this->assertDatabaseHas('audit_logs',['action'=>'withdrawal.capital_paid','entity_id'=>$capital->id]);$this->actingAs($admin)->get('/admin/withdrawals?withdrawal='.$new->id)->assertOk()->assertSee('Обработка заявки на вывод');}
public function test_investor_forbidden_and_stale_status_stays_in_modal():void{[$admin,$investor,$account]=$this->context();$request=$this->request($investor,$account,'approved');$component=Livewire::actingAs($admin)->test(Index::class)->call('openAction',$request->id)->call('requestPaymentConfirmation');$request->update(['status'=>'paid','paid_at'=>now()]);$component->call('confirmPayment')->assertHasErrors('action')->assertSet('showActionModal',true);$this->actingAs($investor->user)->get('/admin/withdrawals')->assertForbidden();}
private function complete(WithdrawalRequest $request,User $admin):void{if($request->type==='dividend')$request->investmentAccount->dailyAccruals()->update(['final_amount'=>'10000.00000000']);$service=app(WithdrawalVerificationService::class);$service->initializeForRequest($request);foreach(WithdrawalVerificationService::MANUAL_KEYS as $key)$service->markPassed($request,$key,$admin);}
private function context():array{$admin=User::factory()->create(['role'=>'admin','is_active'=>true]);$u=User::factory()->create(['role'=>'investor','is_active'=>true]);$i=Investor::create(['user_id'=>$u->id,'code'=>'WITH-ACTION','status'=>'active']);$a=InvestmentAccount::create(['investor_id'=>$i->id,'currency'=>'USDT','status'=>'active']);return[$admin,$i,$a];}
private function request(Investor $i,InvestmentAccount $a,string $status,string $type='dividend'):WithdrawalRequest{return WithdrawalRequest::create(['investor_id'=>$i->id,'investment_account_id'=>$a->id,'type'=>$type,'requested_amount'=>'100','reserved_amount'=>'100','fee_amount'=>'1','fee_payer'=>'investor','fee_economic_type_snapshot'=>'platform_fee','net_amount'=>'99','currency'=>'USDT','wallet_address_snapshot'=>'TFullWalletSnapshot001','network_snapshot'=>'TRC20','status'=>$status,'requested_at'=>now()]);}
private function lot(InvestmentAccount $a,string $amount='1000'):InvestmentLot{return InvestmentLot::firstOrCreate(['investment_account_id'=>$a->id,'original_amount'=>$amount],['remaining_amount'=>$amount,'currency'=>'USDT','received_at'=>now()->subYear(),'accrual_start_date'=>now()->subYear()->toDateString(),'lock_months'=>0,'unlock_date'=>now()->subDay(),'monthly_rate'=>'3','status'=>'active']);}}
