<div class="mx-auto max-w-[1800px]" data-admin-audit>
    <header><h2 class="text-2xl font-semibold tracking-tight">Аудит</h2><p class="mt-1 text-xs text-[#9080ba]">Журнал финансовых и административных действий</p></header>

    <section class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['Событий сегодня',$kpis['today']],['За последние 7 дней',$kpis['week']],['Финансовых действий',$kpis['financial']],['Административных изменений',$kpis['administrative']]] as [$label,$value])<article class="rounded-[18px] border border-white/[.065] bg-[#3c354a] p-4"><p class="text-[10px] text-[#9080ba]">{{ $label }}</p><p class="mt-2 text-2xl font-semibold">{{ $value }}</p></article>@endforeach
    </section>

    <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#3c354a]">
        <div class="grid gap-2 border-b border-white/[.06] bg-[#332c42] p-4 md:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-6">
            <input wire:model.live.debounce.300ms="search" placeholder="Пользователь, инвестор, действие или ID…" class="h-10 rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs outline-none focus:border-cyan-300/40 2xl:col-span-2">
            <select wire:model.live="category" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все категории</option><option value="financial">Финансовые</option><option value="administrative">Административные</option><option value="system">Системные</option></select>
            <select wire:model.live="action" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все действия</option>@foreach($actions as $raw=>$meta)<option value="{{ $raw }}">{{ $meta[0] }}</option>@endforeach</select>
            <select wire:model.live="actorId" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все пользователи</option>@foreach($actors as $actor)<option value="{{ $actor->id }}">{{ $actor->name }}</option>@endforeach</select>
            <select wire:model.live="investorId" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все инвесторы</option>@foreach($investors as $item)<option value="{{ $item->id }}">{{ $item->user->name }} · {{ $item->code }}</option>@endforeach</select>
            <select wire:model.live="objectType" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="">Все объекты</option>@foreach($objectTypes as $type=>$label)<option value="{{ $type }}">{{ $label }}</option>@endforeach</select>
            <select wire:model.live="period" class="h-10 cursor-pointer rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs"><option value="today">Сегодня</option><option value="7">7 дней</option><option value="30">30 дней</option><option value="all">Всё время</option><option value="custom">Произвольный период</option></select>
        </div>
        @if($period==='custom')<form wire:submit="applyCustomPeriod" class="flex flex-col gap-3 border-b border-white/[.06] bg-[#332c42]/70 p-4 sm:flex-row sm:items-end"><label class="flex-1 text-[10px] text-[#a99db6]">Дата от<input type="date" wire:model="customFrom" class="mt-2 h-10 w-full rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs text-white">@error('customFrom')<small class="mt-1 block text-red-300">{{ $message }}</small>@enderror</label><label class="flex-1 text-[10px] text-[#a99db6]">Дата до<input type="date" wire:model="customTo" class="mt-2 h-10 w-full rounded-xl border border-white/[.08] bg-[#2f293e] px-3 text-xs text-white">@error('customTo')<small class="mt-1 block text-red-300">{{ $message }}</small>@enderror</label><button class="h-10 cursor-pointer rounded-xl bg-cyan-300/15 px-4 text-xs text-cyan-200">Применить</button><button type="button" wire:click="resetCustomPeriod" class="h-10 cursor-pointer rounded-xl border border-white/[.09] px-4 text-xs text-[#b9adbf]">Сбросить</button></form>@endif

        <div class="hidden grid-cols-[130px_minmax(150px,1fr)_minmax(170px,1.2fr)_130px_minmax(150px,1fr)_minmax(180px,1.2fr)_36px] gap-3 border-b border-white/[.06] bg-[#332c42] px-5 py-3 text-[9px] uppercase tracking-wide text-[#817590] lg:grid"><span>Дата и время</span><span>Пользователь</span><span>Действие</span><span>Объект</span><span>Инвестор</span><span>Описание</span><span></span></div>
        <div class="divide-y divide-white/[.05]">
            @forelse($logs as $log)
                @php
                    $subject=$subjects[$log->entity_type.'#'.$log->entity_id]??null; $investor=$logInvestors[$log->id]??null;
                    $category=\App\Support\AuditPresentation::category($log->action); $categoryLabel=\App\Support\AuditPresentation::categoryLabel($category);
                    $categoryClass=$category==='financial'?'bg-cyan-300/10 text-cyan-200':($category==='administrative'?'bg-[#ac6aec]/12 text-[#d2a4f5]':'bg-white/[.06] text-[#aaa0b3]');
                    $comparison=\App\Support\AuditPresentation::comparison($log->old_values,$log->new_values);
                    $actorRole=$log->user?->role==='admin'?'Администратор':($log->user?->role==='investor'?'Инвестор':'Система');
                @endphp
                <article x-data="{ expanded:false }" class="bg-[#3a3348]/45 transition hover:bg-white/[.04]">
                    <button type="button" @click="expanded=!expanded" x-bind:aria-expanded="expanded" aria-controls="audit-details-{{ $log->id }}" class="w-full cursor-pointer px-4 py-4 text-left outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-cyan-300/40 lg:px-5">
                        <span class="grid grid-cols-[1fr_auto] gap-2 lg:hidden"><time class="text-[10px] text-[#9080ba]">{{ $log->created_at->format('d.m.Y · H:i') }}</time><span class="rounded-full px-2 py-1 text-[9px] {{ $categoryClass }}">{{ $categoryLabel }}</span><b class="col-span-2 text-xs font-medium">{{ \App\Support\AuditPresentation::label($log->action) }}</b><span class="text-[10px] text-[#a99db6]">{{ $log->user?->name ?: 'Система' }}</span><span class="justify-self-end text-[10px] text-[#9080ba]">Подробнее <span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-block transition">⌄</span></span><span class="text-[10px] text-white">{{ $investor?->user?->name ?: '—' }}</span><span class="truncate text-right text-[10px] text-[#bcb0c5]">{{ \App\Support\AuditPresentation::summary($log,$subject) }}</span></span>
                        <span class="hidden grid-cols-[130px_minmax(150px,1fr)_minmax(170px,1.2fr)_130px_minmax(150px,1fr)_minmax(180px,1.2fr)_36px] items-center gap-3 lg:grid"><time class="text-[10px] text-[#a99db6]">{{ $log->created_at->format('d.m.Y H:i') }}</time><span class="min-w-0"><b class="block truncate text-xs font-medium">{{ $log->user?->name ?: 'Система' }}</b><small class="mt-1 block truncate text-[9px] text-[#817590]">{{ $log->user?->email ?: 'Системное действие' }}</small></span><span><b class="block text-xs font-medium">{{ \App\Support\AuditPresentation::label($log->action) }}</b><small class="mt-1 inline-flex rounded-full px-2 py-0.5 text-[8px] {{ $categoryClass }}">{{ $categoryLabel }}</small></span><span class="text-[10px] text-[#b9adbf]">{{ \App\Support\AuditPresentation::object($log->entity_type) }}</span><span class="min-w-0"><b class="block truncate text-xs font-normal">{{ $investor?->user?->name ?: '—' }}</b><small class="mt-1 block text-[9px] text-[#817590]">{{ $investor?->code ?: '—' }}</small></span><span class="truncate text-[10px] text-[#bcb0c5]">{{ \App\Support\AuditPresentation::summary($log,$subject) }}</span><span aria-hidden="true" :class="expanded&&'rotate-180'" class="inline-flex size-8 items-center justify-center justify-self-end text-[#9080ba] transition">⌄</span></span>
                    </button>
                    <div id="audit-details-{{ $log->id }}" x-show="expanded" x-cloak class="border-t border-white/[.05] bg-[#332c42]/70 p-4 lg:p-5">
                        <p class="text-[9px] font-medium uppercase tracking-[.12em] text-[#766a83]">Основная информация</p>
                        <dl class="mt-3 grid gap-3 text-[10px] sm:grid-cols-2 xl:grid-cols-4"><div><dt class="text-[#817590]">Действие</dt><dd class="mt-1 font-medium text-white">{{ \App\Support\AuditPresentation::label($log->action) }}</dd></div><div><dt class="text-[#817590]">Пользователь</dt><dd class="mt-1 text-white">{{ $log->user?->name ?: 'Система' }} · {{ $log->user?->email ?: '—' }} · {{ $actorRole }}</dd></div><div><dt class="text-[#817590]">Объект</dt><dd class="mt-1 text-white">{{ \App\Support\AuditPresentation::object($log->entity_type) }}</dd></div><div><dt class="text-[#817590]">Инвестор / Время</dt><dd class="mt-1 text-white">{{ $investor?->user?->name ?: '—' }} · {{ $investor?->code ?: '—' }}<br>{{ $log->created_at->format('d.m.Y H:i:s') }}</dd></div></dl>
                        <p class="mt-4 text-[9px] font-medium uppercase tracking-[.12em] text-[#766a83]">Изменения</p>
                        @if($comparison)<div class="mt-2 overflow-hidden rounded-xl border border-white/[.06]"><div class="grid grid-cols-[minmax(120px,1fr)_minmax(100px,1fr)_minmax(100px,1fr)] bg-[#2f293e] px-3 py-2 text-[9px] uppercase text-[#817590]"><span>Параметр</span><span>До</span><span>После</span></div>@foreach($comparison as $row)<div class="grid grid-cols-[minmax(120px,1fr)_minmax(100px,1fr)_minmax(100px,1fr)] gap-2 border-t border-white/[.05] px-3 py-2.5 text-[10px]"><span class="text-[#a99db6]">{{ $row['label'] }}</span><span class="break-all text-[#b9adbf]">{{ $row['old'] }}</span><span class="break-all text-white">{{ $row['new'] }}</span></div>@endforeach</div>@else<p class="mt-2 rounded-xl bg-[#2f293e] p-3 text-[10px] text-[#9080ba]">Изменённые значения не сохранены для этого события.</p>@endif
                        <div class="mt-4 border-t border-white/[.05] pt-3"><p class="text-[9px] font-medium uppercase tracking-[.12em] text-[#6f647b]">Технические данные</p><dl class="mt-2 grid gap-2 text-[9px] text-[#817590] sm:grid-cols-2 xl:grid-cols-3"><div><dt>Технический код</dt><dd class="mt-0.5"><code class="text-[#a99db6]">{{ $log->action }}</code></dd></div><div><dt>Тип объекта</dt><dd class="mt-0.5 truncate" title="{{ $log->entity_type }}"><code class="text-[#a99db6]">{{ $log->entity_type }}</code></dd></div><div><dt>ID объекта</dt><dd class="mt-0.5 text-[#a99db6]">{{ $log->entity_id }}</dd></div><div><dt>IP</dt><dd class="mt-0.5 text-[#a99db6]">{{ $log->ip_address ?: '—' }}</dd></div><div class="sm:col-span-2"><dt>Источник запроса</dt><dd class="mt-0.5 truncate text-[#a99db6]" title="{{ $log->user_agent }}">{{ $log->user_agent ?: '—' }}</dd></div></dl></div>
                    </div>
                </article>
            @empty<div class="px-5 py-14 text-center"><p class="text-sm text-white">События не найдены</p><p class="mt-1 text-[10px] text-[#9080ba]">Измените параметры фильтрации или период.</p></div>@endforelse
        </div>
        @if($logs->hasPages())<div class="border-t border-white/[.06] p-4">{{ $logs->links() }}</div>@endif
    </section>
</div>
