<div class="mx-auto max-w-4xl">
    <div class="mb-5"><a href="{{ route('investor.programs') }}" class="text-xs text-cyan-200">← К программам</a><h2 class="mt-3 text-2xl font-semibold">Новая заявка на пополнение</h2><p class="mt-1 text-sm text-[#9587a7]">Проверьте программу, сумму и предварительный расчёт</p></div>
    @if(!$program||!$version)
        <section class="rounded-[20px] border border-rose-300/15 bg-[#3c354a] p-6"><h3 class="font-semibold text-rose-100">Программа больше недоступна</h3><p class="mt-2 text-sm text-[#9c8faa]">Выберите другую действующую инвестиционную программу.</p><a href="{{ route('investor.programs') }}" class="mt-5 inline-block rounded-xl bg-purple-500 px-4 py-2.5 text-sm">Выбрать программу</a></section>
    @elseif($step===3)
        <section class="rounded-[20px] border border-cyan-300/20 bg-[#3c354a] p-6 text-center"><span class="mx-auto flex size-14 items-center justify-center rounded-full bg-cyan-300/10 text-2xl text-cyan-200">✓</span><h3 class="mt-4 text-xl font-semibold">Заявка создана</h3><p class="mt-2 text-sm text-[#9587a7]">Программа: <b class="text-white">{{ $program->name }}</b></p><p class="mt-1 text-sm text-[#9587a7]">Статус: <span class="text-cyan-100">Ожидает пополнения</span></p><a href="{{ route('investor.finance') }}" class="mt-6 inline-block rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-5 py-3 text-sm font-semibold">Перейти в финансы</a></section>
    @else
        <section class="rounded-[20px] border border-white/[.07] bg-[#3c354a] p-5 sm:p-6">
            <div class="flex flex-col gap-4 border-b border-white/[.06] pb-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs text-[#9183a2]">Выбранная программа</p><h3 class="mt-1 text-xl font-semibold">{{ $program->name }}</h3><p class="mt-1 text-xs text-[#8b7e99]">{{ $program->description }}</p></div><span class="w-fit rounded-xl bg-cyan-300/10 px-3 py-2 text-xs text-cyan-100">{{ $program->currency }}</span></div>
            <div class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-2xl bg-white/[.025] p-4"><p class="text-xs text-[#9183a2]">Доходность</p><p class="mt-2 font-semibold">{{ \App\Support\InvestmentTermPresentation::rate((string)($effectiveTerms['rate']??$version->monthly_rate)) }} в месяц</p><p class="mt-1 text-[10px] text-cyan-200">{{ ($effectiveTerms['source']??'program')==='individual'?'Individual Investor Term':'Investment Program' }}</p></div><div class="rounded-2xl bg-white/[.025] p-4"><p class="text-xs text-[#9183a2]">Срок инвестирования</p><p class="mt-2 font-semibold">{{ $effectiveTerms['term_months']??$version->lock_months }} месяцев</p></div><div class="rounded-2xl bg-white/[.025] p-4"><p class="text-xs text-[#9183a2]">Период блокировки</p><p class="mt-2 font-semibold">{{ ($effectiveTerms['lock_days']??null)!==null?$effectiveTerms['lock_days'].' дней':$version->lock_months.' месяцев' }}</p></div><div class="rounded-2xl bg-white/[.025] p-4"><p class="text-xs text-[#9183a2]">Частичный вывод</p><p class="mt-2 font-semibold">{{ ($effectiveTerms['partial_withdrawal']??$program->is_partial_withdrawal_allowed)?'Да':'Нет' }}</p></div></div>
            @if($step===1)
                <div class="mt-6"><label class="text-sm font-medium">Сумма инвестиции</label><div class="relative mt-2"><input wire:model.live.debounce.300ms="amount" inputmode="decimal" placeholder="7000" class="w-full rounded-xl border border-white/10 bg-[#2f293e] py-3 pl-4 pr-16 text-lg outline-none focus:border-cyan-300/40"><span class="absolute right-4 top-1/2 -translate-y-1/2 text-xs text-[#9080ba]">{{ $program->currency }}</span></div>@error('amount')<p class="mt-2 text-sm text-rose-200">{{ $message }}</p>@enderror @error('program')<p class="mt-2 text-sm text-rose-200">{{ $message }}</p>@enderror</div>
                @if($belowMinimum)<div class="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-sm"><p class="font-medium text-amber-100">Минимальная инвестиция для программы {{ $program->name }} — {{ \App\Support\MoneyFormatter::format($program->min_amount,0) }} {{ $program->currency }}</p><p class="mt-2 text-[#b7aabc]">Ваша сумма — {{ \App\Support\MoneyFormatter::format($amount) }} {{ $program->currency }}</p><p class="mt-1 text-[#b7aabc]">Необходимо добавить {{ \App\Support\MoneyFormatter::format($shortfall) }} {{ $program->currency }}</p></div>@elseif($aboveMaximum)<div class="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-sm"><p class="font-medium text-amber-100">Максимальная сумма программы — {{ \App\Support\MoneyFormatter::format($program->max_amount,0) }} {{ $program->currency }}</p>@if($suggestedPrograms->isNotEmpty())<p class="mt-3 text-[#b7aabc]">Для этой суммы подойдут:</p><div class="mt-2 flex flex-wrap gap-2">@foreach($suggestedPrograms as $suggested)<a href="{{ route('investor.finance.create',['investment_program_id'=>$suggested->id,'amount'=>$amount]) }}" class="rounded-lg bg-white/[.06] px-3 py-2 text-cyan-100">{{ $suggested->name }}</a>@endforeach</div>@endif<a href="{{ route('investor.programs') }}" class="mt-3 inline-block text-cyan-200">Выбрать другую программу →</a></div>@elseif($projection)<div class="mt-5 rounded-2xl border border-emerald-300/15 bg-emerald-300/[.045] p-4"><p class="mb-3 text-sm font-medium text-emerald-100">Сумма подходит для этой программы</p><div class="grid gap-3 sm:grid-cols-3"><div><p class="text-xs text-[#9183a2]">Инвестиция</p><b>{{ \App\Support\MoneyFormatter::format($amount) }} {{ $program->currency }}</b></div><div><p class="text-xs text-[#9183a2]">Начисление</p><b>{{ \App\Support\MoneyFormatter::format($projection['monthly']) }} {{ $program->currency }} / месяц</b></div><div><p class="text-xs text-[#9183a2]">Прогноз дохода за срок</p><b>{{ \App\Support\MoneyFormatter::format($projection['period']) }} {{ $program->currency }}</b></div></div></div>@endif
                <p class="mt-4 text-xs leading-5 text-[#887a99]">Расчёт является предварительным. Финальные условия фиксируются после подтверждения инвестиции.</p><div class="mt-6 flex justify-end">@if($belowMinimum)<button type="button" wire:click="useMinimum" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-5 py-3 text-sm font-semibold">Инвестировать {{ \App\Support\MoneyFormatter::format($program->min_amount,0) }} {{ $program->currency }}</button>@elseif(!$aboveMaximum)<button type="button" wire:click="review" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-5 py-3 text-sm font-semibold">Продолжить</button>@endif</div>
            @else
                <div class="mt-6 rounded-2xl border border-white/[.07] bg-[#2f293e] p-5"><h4 class="font-semibold">Проверьте данные</h4><dl class="mt-4 space-y-3 text-sm"><div class="flex justify-between"><dt class="text-[#9183a2]">Программа</dt><dd class="font-semibold">{{ $program->name }}</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Источник условий</dt><dd>{{ ($effectiveTerms['source']??'program')==='individual'?'Individual Investor Term':'Investment Program' }}</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Сумма</dt><dd class="font-semibold">{{ \App\Support\MoneyFormatter::format($amount) }} {{ $program->currency }}</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Ставка</dt><dd>{{ \App\Support\InvestmentTermPresentation::rate((string)($effectiveTerms['rate']??$version->monthly_rate)) }}</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Срок</dt><dd>{{ $effectiveTerms['term_months']??$version->lock_months }} месяцев</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Период блокировки</dt><dd>{{ ($effectiveTerms['lock_days']??null)!==null?$effectiveTerms['lock_days'].' дней':$version->lock_months.' месяцев' }}</dd></div><div class="flex justify-between"><dt class="text-[#9183a2]">Прогноз дохода</dt><dd class="font-semibold">{{ \App\Support\MoneyFormatter::format($projection['period']) }} {{ $program->currency }}</dd></div></dl></div><div class="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" wire:click="back" class="cursor-pointer rounded-xl border border-white/10 px-5 py-3 text-sm">Назад</button><button type="button" wire:click="submit" wire:loading.attr="disabled" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-5 py-3 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-60">Подтвердить и создать заявку</button></div>
            @endif
        </section>
    @endif
</div>
