@php use App\Support\MoneyFormatter; use App\Support\InvestorPresentation; @endphp
<div class="mx-auto max-w-[1500px] space-y-5">
    @if(session('success'))<div id="investor-operation-toast" role="status" class="fixed right-4 top-20 z-[80] max-w-[calc(100vw-2rem)] rounded-2xl border border-cyan-200/15 bg-[#332b42]/95 px-4 py-3 text-sm text-cyan-50 shadow-2xl backdrop-blur-xl sm:right-6">{{ session('success') }}</div><script>setTimeout(()=>document.getElementById('investor-operation-toast')?.remove(),4500)</script>@endif
    <section class="relative overflow-hidden rounded-[22px] border border-white/[.08] bg-[#3c354a] p-5 sm:p-6"><div class="absolute -right-24 -top-24 size-72 rounded-full bg-purple-500/15 blur-3xl"></div><div class="relative grid gap-5 lg:grid-cols-[1fr_auto] lg:items-end"><div><div class="mb-4 flex items-center gap-4"><div class="flex size-14 items-center justify-center rounded-2xl bg-gradient-to-br from-[#b773f0] to-[#58c8df] text-xl font-bold">{{ mb_strtoupper(mb_substr($investor->user->name,0,1)) }}</div><div><h2 class="text-2xl font-semibold">{{ $investor->user->name }}</h2><p class="text-sm text-[#a99abc]">{{ $investor->code ?? 'Без кода' }} · <span class="text-emerald-300">{{ InvestorPresentation::status($investor->status) }}</span></p></div></div><div class="flex flex-wrap items-end gap-x-8 gap-y-3"><div><p class="text-xs uppercase tracking-wider text-[#8f80aa]">Инвестиционный капитал</p><p class="mt-1 text-3xl font-semibold">{{ MoneyFormatter::format($summary['capital']) }} <span class="text-base text-[#a99abc]">USDT</span></p></div><div><p class="text-xs text-[#8f80aa]">Текущая ставка</p><p class="mt-1 text-xl font-semibold text-cyan-200">{{ MoneyFormatter::format($summary['rate']) }}%</p></div></div></div><div class="grid grid-cols-2 gap-3 lg:min-w-[320px]"><div class="rounded-2xl border border-purple-300/10 bg-white/[.035] px-4 py-3"><p class="text-[11px] text-[#9f92b0]">Доступно дивидендов</p><p class="mt-1 text-lg font-semibold text-cyan-100">{{ MoneyFormatter::format($summary['availableDividends']) }}</p><p class="text-[10px] text-[#81738f]">USDT</p></div><div class="rounded-2xl border border-cyan-300/10 bg-white/[.035] px-4 py-3"><p class="text-[11px] text-[#9f92b0]">Капитал к выводу</p><p class="mt-1 text-lg font-semibold text-cyan-100">{{ MoneyFormatter::format($summary['availableCapital']) }}</p><p class="text-[10px] text-[#81738f]">USDT</p></div></div></div></section>

    <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @php $kpis = ['today'=>'Начислено сегодня','month'=>'За текущий месяц','total'=>'За всё время','paid'=>'Выплачено дивидендов','availableDividends'=>'Доступно дивидендов','lockedCapital'=>'Заблокированный капитал','availableCapital'=>'Капитал к выводу']; if($periodMode==='custom' && $periodFrom && $periodTo && !$errors->has('periodFrom') && !$errors->has('periodTo')) $kpis = array_slice($kpis,0,3,true)+['period'=>'За период '.\Carbon\Carbon::parse($periodFrom)->format('d.m.Y').' — '.\Carbon\Carbon::parse($periodTo)->format('d.m.Y')]+array_slice($kpis,3,null,true); @endphp
        @foreach($kpis as $key=>$label)
            <div class="rounded-[18px] border border-white/[.07] bg-[#3c354a] p-4"><p class="text-xs text-[#9a8cac]">{{ $label }}</p><p class="mt-2 text-xl font-semibold {{ in_array($key,['availableDividends','availableCapital']) ? 'text-cyan-200' : '' }}">{{ MoneyFormatter::format($summary[$key]) }} <span class="text-xs font-normal text-[#88799e]">USDT</span></p>@if($key==='lockedCapital' && $nearestUnlock)<p class="mt-1 text-[10px] text-[#897b9b]">до {{ \Carbon\Carbon::parse($nearestUnlock)->format('d.m.Y') }}</p>@endif</div>
        @endforeach
    </div>

    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-[1.25fr_1fr_1fr_1fr]"><button wire:click="openDialog('capitalization')" class="rounded-2xl bg-gradient-to-r from-[#9b62e4] via-[#825ddd] to-[#4ebdd5] px-5 py-4 text-sm font-semibold shadow-lg shadow-purple-950/30 transition hover:-translate-y-px hover:brightness-110">Перевести в капитал</button><button wire:click="openDialog('dividend')" class="rounded-2xl border border-purple-300/15 bg-[#3c354a] px-5 py-4 text-sm font-medium hover:bg-white/[.055]">Вывести дивиденды</button><button wire:click="openDialog('capital')" @disabled($summary['availableCapital']==='0.00000000') class="rounded-2xl border border-white/10 bg-[#3c354a] px-5 py-4 text-sm disabled:cursor-not-allowed disabled:opacity-45">Вывести капитал</button><a href="{{ route('investor.wallets') }}" class="rounded-2xl border border-white/10 bg-[#3c354a] px-5 py-4 text-center text-sm">Мои кошельки</a>@if($summary['availableCapital']==='0.00000000' && $nearestUnlock)<p class="sm:col-span-2 xl:col-span-4 text-xs text-[#9a8cac]">Ближайшая разблокировка: {{ \Carbon\Carbon::parse($nearestUnlock)->format('d.m.Y') }}</p>@endif</section>

    <section class="rounded-[20px] border border-white/[.07] bg-[#3c354a] p-4 sm:p-6"><div class="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><h3 class="text-lg font-semibold">Динамика начислений</h3><p class="mt-1 text-xs text-[#9486a6]">Начисления по всем инвестициям суммированы за каждый день</p></div><div class="flex flex-col gap-3 xl:items-end"><div class="text-left xl:text-right"><p class="text-[11px] text-[#8f819f]">Начислено за период</p><p class="mt-0.5 text-lg font-semibold text-cyan-100">{{ MoneyFormatter::format($summary['period']) }} <span class="text-xs font-normal text-[#8b7d99]">USDT</span></p></div><div class="w-full overflow-x-auto pb-1 xl:w-auto"><div class="min-w-max xl:min-w-0">@include('livewire.investor.partials.period', ['dashboardPeriod' => true])</div></div></div></div><div class="relative"><div class="pointer-events-none absolute left-1 top-3 z-10 flex h-32 flex-col justify-between text-[9px] text-[#756986]"><span>{{ MoneyFormatter::format($chartMaximum) }}</span><span>0.00</span></div><div class="pl-8">@include('livewire.investor.partials.chart', ['compactChart' => true])</div></div></section>

    <section class="rounded-[20px] border border-white/[.07] bg-[#3c354a] p-4 sm:p-6"><div class="flex items-center justify-between"><h3 class="text-lg font-semibold">Последние операции</h3><a href="{{ route('investor.finance') }}" class="text-xs text-cyan-200 hover:text-cyan-100">Все операции →</a></div><div class="mt-4 space-y-2">@forelse($history as $item)@php $iconPath = match($item['kind']) {'deposit'=>'M12 3v12m-5-5 5 5 5-5M5 21h14','capitalization'=>'M4 12a8 8 0 1 0 2.3-5.7M4 4v5h5','capital_withdrawal'=>'M12 21V9m5 5-5-5-5 5','dividend_withdrawal'=>'M12 3v12m5-5-5 5-5-5M5 21h14','payment'=>'m4 12 5 5L20 6',default=>'M4 12h16'}; @endphp<div class="flex items-center gap-3 rounded-2xl bg-white/[.035] px-3 py-3 sm:px-4"><span class="flex size-10 shrink-0 items-center justify-center rounded-xl border border-cyan-200/10 bg-cyan-200/[.055] text-cyan-200"><svg viewBox="0 0 24 24" class="size-[18px]" fill="none" stroke="currentColor" stroke-width="1.7"><path d="{{ $iconPath }}"/></svg></span><div class="min-w-0 flex-1"><p class="truncate text-sm font-medium">{{ $item['label'] }}</p><p class="mt-0.5 text-xs text-[#8f80a1]">{{ $item['date']->format('d.m.Y') }} · {{ InvestorPresentation::status($item['status']) }}</p></div><p class="shrink-0 text-right text-sm font-semibold">{{ MoneyFormatter::format($item['amount']) }} <span class="hidden text-[10px] font-normal text-[#81748e] sm:inline">USDT</span></p></div>@empty<p class="text-sm text-[#8f80a1]">Операций пока нет.</p>@endforelse</div></section>

    @if($dialog)
        @include('livewire.investor.partials.financial-modal')
    @endif
    @if(false && $dialog)
        <div class="fixed inset-0 z-[70] flex items-end justify-center bg-[#16101f]/85 p-3 backdrop-blur-sm sm:items-center" wire:click.self="closeDialog"><div class="max-h-[92vh] w-full max-w-lg overflow-y-auto rounded-[22px] border border-white/10 bg-[#3c354a] p-5 shadow-2xl sm:p-6">
            <div class="flex justify-between"><div><h3 class="text-xl font-semibold">{{ $dialog==='capitalization' ? 'Перевести в капитал' : ($dialog==='capital' ? 'Вывести капитал' : 'Вывести дивиденды') }}</h3><p class="mt-1 text-xs text-[#9b8dac]">Проверьте сумму и итоговые условия</p></div><button wire:click="closeDialog" class="size-9 rounded-xl bg-white/5">×</button></div>
            @if($dialog==='capitalization')
                <div class="mt-5 rounded-2xl bg-[#2c2538] p-4"><p class="text-xs text-[#9b8dac]">Доступно дивидендов</p><p class="mt-1 text-xl">{{ MoneyFormatter::format($summary['availableDividends']) }} USDT</p></div><label class="mt-4 block text-xs text-[#a99abc]">Сумма капитализации<div class="mt-1 flex gap-2"><input wire:model.live.debounce.350ms="capitalizationAmount" inputmode="decimal" class="min-w-0 flex-1 rounded-xl border border-white/10 bg-[#292235] px-3 py-3"><button wire:click="useAllDividends" class="rounded-xl border border-cyan-300/20 px-3 text-xs text-cyan-200">Вся сумма</button></div></label>@error('capitalizationAmount')<p class="mt-2 text-xs text-rose-300">{{ $message }}</p>@enderror
                <div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Комиссия</p><p class="mt-1">{{ MoneyFormatter::format($capitalizationPreview['fee_amount'] ?? '0') }} USDT</p></div><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">В новую инвестицию</p><p class="mt-1 text-cyan-200">{{ MoneyFormatter::format($capitalizationPreview['net_amount'] ?? '0') }} USDT</p></div><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Ставка</p><p class="mt-1">{{ MoneyFormatter::format($term?->monthly_rate) }}%</p></div><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Блокировка</p><p class="mt-1">{{ $term?->lock_months ?? '—' }} мес.</p></div><div class="col-span-2 rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Начало начислений</p><p class="mt-1">{{ now()->addDay()->format('d.m.Y') }}</p></div></div><button wire:click="capitalize" class="mt-5 w-full rounded-xl bg-gradient-to-r from-[#8d61ed] to-[#4ebdd5] px-4 py-3 font-semibold">Подтвердить капитализацию</button>
            @else
                <div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-[#2c2538] p-4"><p class="text-xs text-[#9b8dac]">Доступно</p><p class="mt-1 text-lg">{{ MoneyFormatter::format($dialog==='capital' ? $summary['availableCapital'] : $summary['availableDividends']) }} USDT</p></div><div class="rounded-2xl bg-[#2c2538] p-4"><p class="text-xs text-[#9b8dac]">Заблокировано</p><p class="mt-1 text-lg">{{ MoneyFormatter::format($dialog==='capital' ? $summary['lockedCapital'] : '0') }} USDT</p></div></div>
                @if($wallets->isEmpty())<div class="mt-4 rounded-2xl border border-amber-300/15 bg-amber-300/[.06] p-4 text-sm text-amber-100">Нет подтверждённого кошелька. <a href="{{ route('investor.wallets') }}" class="underline">Перейти в кошельки</a>.</div>@else<label class="mt-4 block text-xs text-[#a99abc]">Сумма<input wire:model.live.debounce.350ms="withdrawalAmount" inputmode="decimal" class="mt-1 w-full rounded-xl border border-white/10 bg-[#292235] px-3 py-3"></label>@error('withdrawalAmount')<p class="mt-2 text-xs text-rose-300">{{ $message }}</p>@enderror<label class="mt-4 block text-xs text-[#a99abc]">Кошелёк<select wire:model="walletId" class="mt-1 w-full rounded-xl border border-white/10 bg-[#292235] px-3 py-3">@foreach($wallets as $wallet)<option value="{{ $wallet->id }}">{{ $wallet->network }} · {{ $wallet->address }}</option>@endforeach</select></label>@error('walletId')<p class="mt-2 text-xs text-rose-300">{{ $message }}</p>@enderror<div class="mt-4 grid grid-cols-2 gap-3 text-sm"><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">Комиссия</p><p class="mt-1">{{ MoneyFormatter::format($withdrawalPreview['fee_amount'] ?? '0') }} USDT</p></div><div class="rounded-xl bg-white/[.035] p-3"><p class="text-xs text-[#9587a7]">К выплате</p><p class="mt-1 text-cyan-200">{{ MoneyFormatter::format($withdrawalPreview['net_amount'] ?? '0') }} USDT</p></div></div><button wire:click="{{ $dialog==='capital' ? 'requestCapitalWithdrawal' : 'requestDividendWithdrawal' }}" class="mt-5 w-full rounded-xl bg-gradient-to-r from-[#8d61ed] to-[#4ebdd5] px-4 py-3 font-semibold">Отправить заявку</button>@endif
            @endif
        </div></div>
    @endif
</div>
