<div class="mx-auto max-w-5xl">
    <div class="mb-5"><a href="{{ route('admin.investors.index') }}" wire:navigate class="inline-flex items-center gap-2 text-xs text-[#9183a5] transition hover:text-[#c18def]">← Вернуться к инвесторам</a><h2 class="mt-4 text-[24px] font-semibold tracking-tight text-white">Новый инвестор</h2><p class="mt-1 text-xs text-[#8f82a6]">Создание профиля и инвестиционного счета</p></div>

    <form wire:submit="save" class="overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43] shadow-[0_24px_60px_rgba(20,12,32,.12)]">
        <section class="border-b border-white/[.06] p-5 sm:p-6"><div class="mb-5 flex items-center gap-3"><span class="flex size-9 items-center justify-center rounded-2xl bg-[#a968dc]/12 text-[#c792ef]"><svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/></svg></span><div><h3 class="text-sm font-semibold text-white">Личные данные</h3><p class="mt-0.5 text-[10px] text-[#82758f]">Основная информация и доступ к системе</p></div></div><div class="grid gap-4 md:grid-cols-2">
            @foreach([['name','Имя','text','Имя и фамилия'],['email','Email','email','investor@example.com'],['password','Пароль','password','Не менее 8 символов'],['phone','Телефон','text','+7 900 000-00-00']] as [$field,$label,$type,$placeholder])<label><span class="mb-2 block text-[11px] text-[#a99bb9]">{{ $label }}</span><input wire:model="{{ $field }}" type="{{ $type }}" placeholder="{{ $placeholder }}" class="h-11 w-full rounded-2xl border border-white/[.07] bg-[#292236] px-4 text-sm text-white placeholder:text-[#685d75] focus:border-[#ac6aec]/50">@error($field)<span class="mt-1.5 block text-[10px] text-rose-300">{{ $message }}</span>@enderror</label>@endforeach
        </div></section>

        <section class="border-b border-white/[.06] p-5 sm:p-6"><div class="mb-5 flex items-center gap-3"><span class="flex size-9 items-center justify-center rounded-2xl bg-cyan-300/10 text-cyan-300"><svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16v12H4zM8 10h8M8 14h5"/></svg></span><div><h3 class="text-sm font-semibold text-white">Инвестиционный профиль</h3><p class="mt-0.5 text-[10px] text-[#82758f]">Идентификатор и начальный статус инвестора</p></div></div><div class="grid gap-4 md:grid-cols-2"><label><span class="mb-2 block text-[11px] text-[#a99bb9]">Код инвестора</span><input wire:model="code" placeholder="INV-001" class="h-11 w-full rounded-2xl border border-white/[.07] bg-[#292236] px-4 text-sm text-white placeholder:text-[#685d75] focus:border-[#ac6aec]/50">@error('code')<span class="mt-1.5 block text-[10px] text-rose-300">{{ $message }}</span>@enderror</label><label><span class="mb-2 block text-[11px] text-[#a99bb9]">Статус</span><select wire:model="status" class="h-11 w-full rounded-2xl border border-white/[.07] bg-[#292236] px-4 text-sm text-white focus:border-[#ac6aec]/50"><option value="active">Активный</option><option value="inactive">Неактивный</option><option value="suspended">Приостановлен</option></select>@error('status')<span class="mt-1.5 block text-[10px] text-rose-300">{{ $message }}</span>@enderror</label></div></section>

        <section class="p-5 sm:p-6"><div class="mb-5 flex items-center gap-3"><span class="flex size-9 items-center justify-center rounded-2xl bg-[#fa829b]/10 text-[#fa9bae]"><svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM14 3v4h4M9 12h6M9 16h4"/></svg></span><div><h3 class="text-sm font-semibold text-white">Договор</h3><p class="mt-0.5 text-[10px] text-[#82758f]">Реквизиты инвестиционного договора</p></div></div><div class="grid gap-4 md:grid-cols-2"><label><span class="mb-2 block text-[11px] text-[#a99bb9]">Номер договора</span><input wire:model="contractNumber" placeholder="CM-2026-001" class="h-11 w-full rounded-2xl border border-white/[.07] bg-[#292236] px-4 text-sm text-white placeholder:text-[#685d75] focus:border-[#ac6aec]/50">@error('contractNumber')<span class="mt-1.5 block text-[10px] text-rose-300">{{ $message }}</span>@enderror</label><label><span class="mb-2 block text-[11px] text-[#a99bb9]">Дата договора</span><input wire:model="contractDate" type="date" class="h-11 w-full rounded-2xl border border-white/[.07] bg-[#292236] px-4 text-sm text-white focus:border-[#ac6aec]/50">@error('contractDate')<span class="mt-1.5 block text-[10px] text-rose-300">{{ $message }}</span>@enderror</label></div></section>

        <div class="flex flex-col-reverse gap-3 border-t border-white/[.06] bg-[#30283d] p-4 sm:flex-row sm:justify-end sm:px-6"><a href="{{ route('admin.investors.index') }}" wire:navigate class="rounded-2xl border border-white/[.08] px-5 py-2.5 text-center text-xs text-[#b1a4bf] transition hover:bg-white/[.04]">Отмена</a><button class="rounded-2xl bg-gradient-to-r from-[#a766dc] to-[#8261e8] px-5 py-2.5 text-xs font-medium text-white shadow-lg shadow-purple-950/20 transition hover:brightness-110">Создать инвестора</button></div>
    </form>
</div>
