<div class="mx-auto max-w-[1800px]">
    <div class="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end">
        <div><h2 class="text-[24px] font-semibold tracking-tight text-white">Инвесторы</h2><p class="mt-1 text-xs text-[#8f82a6]">Управление инвестиционными счетами CEO Money</p></div>
        <a href="{{ route('admin.investors.create') }}" wire:navigate class="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-[#a766dc] to-[#8261e8] px-4 py-2.5 text-sm font-medium text-white shadow-lg shadow-purple-950/20 transition hover:brightness-110"><span class="text-lg leading-none">+</span> Добавить инвестора</a>
    </div>

    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @foreach($summary as $index => [$label, $value, $money])
            <article class="relative overflow-hidden rounded-[18px] border border-white/[.065] bg-[#352e43] p-4"><div class="absolute right-0 top-0 size-20 bg-gradient-to-bl {{ $index % 2 ? 'from-cyan-300/[.07]' : 'from-purple-400/[.09]' }} to-transparent"></div><div class="relative flex items-start justify-between"><div><p class="text-[11px] text-[#9487a8]">{{ $label }}</p><p class="mt-3 text-[24px] font-semibold tracking-tight text-white">{{ $money ? \App\Support\MoneyFormatter::format($value) : $value }} @if($money)<span class="text-[10px] font-normal text-[#776a8a]">USDT</span>@endif</p></div><span class="flex size-8 items-center justify-center rounded-xl bg-white/[.04] {{ $index % 2 ? 'text-cyan-300' : 'text-[#c28def]' }}">{{ str_pad($index + 1, 2, '0', STR_PAD_LEFT) }}</span></div></article>
        @endforeach
    </section>

    <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]">
        <div class="grid gap-3 border-b border-white/[.06] p-4 md:grid-cols-[minmax(260px,1fr)_180px_170px_120px]">
            <label class="flex items-center gap-2 rounded-2xl border border-white/[.07] bg-[#292236] px-3.5"><svg viewBox="0 0 24 24" class="size-4 text-[#827495]" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input wire:model.live.debounce.300ms="search" placeholder="Имя, email или код…" class="h-10 min-w-0 flex-1 bg-transparent text-xs text-white placeholder:text-[#716580]"></label>
            <select wire:model.live="status" class="h-10 rounded-2xl border border-white/[.07] bg-[#292236] px-3 text-xs text-[#b7aac6]"><option value="">Все статусы</option><option value="active">Активные</option><option value="inactive">Неактивные</option><option value="suspended">Приостановлены</option></select>
            <select wire:model.live="sortBy" class="h-10 rounded-2xl border border-white/[.07] bg-[#292236] px-3 text-xs text-[#b7aac6]"><option value="created_at">Дата регистрации</option><option value="code">Код</option><option value="status">Статус</option></select>
            <select wire:model.live="sortDirection" class="h-10 rounded-2xl border border-white/[.07] bg-[#292236] px-3 text-xs text-[#b7aac6]"><option value="desc">Сначала новые</option><option value="asc">Сначала старые</option></select>
        </div>

        <div class="hidden overflow-x-auto md:block">
            <table class="w-full min-w-[1180px] text-left text-xs"><thead class="border-b border-white/[.06] bg-[#30283d] text-[10px] uppercase tracking-[.08em] text-[#7f728f]"><tr><th class="px-4 py-3.5">Код</th><th class="px-4 py-3.5">Инвестор</th><th class="px-4 py-3.5">Email</th><th class="px-4 py-3.5">Статус</th><th class="px-4 py-3.5 text-right">Капитал</th><th class="px-4 py-3.5 text-right">Ставка</th><th class="px-4 py-3.5 text-right">Начислено</th><th class="px-4 py-3.5 text-right">Доступно</th><th class="px-4 py-3.5">Регистрация</th><th class="w-10"></th></tr></thead>
            <tbody class="divide-y divide-white/[.045]">@forelse($investors as $investor) @php $accounts=$investor->investmentAccounts; $calculator=app(\App\Services\AccrualCalculator::class); $capital=$accounts->flatMap->investmentLots->pluck('remaining_amount')->reduce(fn($c,$v)=>$calculator->add($c,(string)$v),'0.00000000'); $accrued=$accounts->flatMap->dailyAccruals->pluck('final_amount')->reduce(fn($c,$v)=>$calculator->add($c,(string)$v),'0.00000000'); $available=$accounts->reduce(fn($c,$a)=>$calculator->add($c,app(\App\Services\AvailableBalanceService::class)->availableDividendBalance($a)),'0.00000000'); $rate=$accounts->flatMap->investmentLots->where('status','active')->first()?->monthly_rate ?? '0.0000'; $initial=mb_strtoupper(mb_substr($investor->user->name,0,1)); @endphp
                <tr onclick="window.location='{{ route('admin.investors.show',$investor) }}'" class="cursor-pointer transition hover:bg-white/[.035]"><td class="px-4 py-4 font-medium text-[#c18def]">{{ $investor->code ?: '—' }}</td><td class="px-4 py-4"><div class="flex items-center gap-3"><span class="flex size-9 items-center justify-center rounded-full bg-gradient-to-br from-[#a967dd] to-[#4b91c7] text-xs font-semibold text-white">{{ $initial }}</span><span class="font-medium text-white">{{ $investor->user->name }}</span></div></td><td class="px-4 py-4 text-[#9588a6]">{{ $investor->user->email }}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-[10px] {{ $investor->status==='active' ? 'bg-emerald-400/10 text-emerald-300' : ($investor->status==='suspended' ? 'bg-amber-300/10 text-amber-200' : 'bg-slate-400/10 text-slate-300') }}">{{ $investor->status }}</span></td><td class="px-4 py-4 text-right font-medium text-white">{{ \App\Support\MoneyFormatter::format($capital) }}</td><td class="px-4 py-4 text-right text-cyan-300">{{ $rate }}%</td><td class="px-4 py-4 text-right text-[#b7a9c6]">{{ \App\Support\MoneyFormatter::format($accrued) }}</td><td class="px-4 py-4 text-right text-[#b7a9c6]">{{ \App\Support\MoneyFormatter::format($available) }}</td><td class="px-4 py-4 text-[#857891]">{{ $investor->created_at->format('d.m.Y') }}</td><td class="px-4 py-4 text-[#786b89]">→</td></tr>
            @empty<tr><td colspan="10" class="px-5 py-14 text-center text-[#81748f]">Инвесторы не найдены</td></tr>@endforelse</tbody></table>
        </div>

        <div class="divide-y divide-white/[.05] md:hidden">@forelse($investors as $investor) @php $accounts=$investor->investmentAccounts; $calculator=app(\App\Services\AccrualCalculator::class); $capital=$accounts->flatMap->investmentLots->pluck('remaining_amount')->reduce(fn($c,$v)=>$calculator->add($c,(string)$v),'0.00000000'); $available=$accounts->reduce(fn($c,$a)=>$calculator->add($c,app(\App\Services\AvailableBalanceService::class)->availableDividendBalance($a)),'0.00000000'); @endphp
            <a href="{{ route('admin.investors.show',$investor) }}" wire:navigate class="block p-4 transition hover:bg-white/[.03]"><div class="flex items-start gap-3"><span class="flex size-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#a967dd] to-[#4b91c7] text-sm font-semibold">{{ mb_strtoupper(mb_substr($investor->user->name,0,1)) }}</span><div class="min-w-0 flex-1"><div class="flex items-start justify-between gap-2"><div><p class="truncate text-sm font-medium text-white">{{ $investor->user->name }}</p><p class="truncate text-[11px] text-[#8c7f9d]">{{ $investor->user->email }}</p></div><span class="rounded-full px-2 py-1 text-[9px] {{ $investor->status==='active' ? 'bg-emerald-400/10 text-emerald-300' : 'bg-slate-400/10 text-slate-300' }}">{{ $investor->status }}</span></div><div class="mt-4 grid grid-cols-2 gap-3"><div><p class="text-[9px] uppercase text-[#71657f]">Капитал</p><p class="mt-1 text-xs font-medium">{{ \App\Support\MoneyFormatter::format($capital) }} USDT</p></div><div><p class="text-[9px] uppercase text-[#71657f]">Доступно</p><p class="mt-1 text-xs font-medium">{{ \App\Support\MoneyFormatter::format($available) }} USDT</p></div><div><p class="text-[9px] uppercase text-[#71657f]">Код</p><p class="mt-1 text-xs text-[#c18def]">{{ $investor->code ?: '—' }}</p></div><div><p class="text-[9px] uppercase text-[#71657f]">Регистрация</p><p class="mt-1 text-xs text-[#a99bb8]">{{ $investor->created_at->format('d.m.Y') }}</p></div></div></div><span class="mt-2 text-[#746685]">→</span></div></a>
        @empty<div class="p-12 text-center text-xs text-[#81748f]">Инвесторы не найдены</div>@endforelse</div>
        <div class="border-t border-white/[.06] px-4 py-3">{{ $investors->links() }}</div>
    </section>
</div>
