<div class="mx-auto max-w-[1800px]">
    <a href="{{ route('admin.investors.index') }}" wire:navigate class="inline-flex items-center gap-2 text-xs text-[#9183a5] transition hover:text-[#c18def]">← Вернуться к инвесторам</a>
    <header class="mt-4 flex items-start gap-4"><div class="flex size-14 shrink-0 items-center justify-center rounded-[18px] bg-gradient-to-br from-[#ac6aec] to-[#4c97ce] text-xl font-semibold shadow-lg shadow-purple-950/20">{{ mb_strtoupper(mb_substr($investor->user->name,0,1)) }}</div><div class="min-w-0"><div class="flex flex-wrap items-center gap-2.5"><h2 class="truncate text-[24px] font-semibold tracking-tight text-white">{{ $investor->user->name }}</h2><span class="rounded-full px-2.5 py-1 text-[10px] {{ $investor->status==='active' ? 'bg-emerald-400/10 text-emerald-300' : ($investor->status==='suspended' ? 'bg-amber-300/10 text-amber-200' : 'bg-slate-400/10 text-slate-300') }}">{{ $investor->status }}</span></div><p class="mt-1 truncate text-xs text-[#9789a9]">{{ $investor->user->email }}</p><div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-[#786b89]"><span>Код: <b class="font-medium text-[#bc89e9]">{{ $investor->code ?: '—' }}</b></span><span>Договор: {{ $investor->contract_number ?: '—' }}</span><span>Регистрация: {{ $investor->created_at->format('d.m.Y') }}</span></div></div></header>

    @if($currentTerm)
        <div class="mt-4 flex flex-wrap gap-x-6 gap-y-2 rounded-2xl border border-white/[.06] bg-[#332c42]/70 px-4 py-3 text-[10px] text-[#9080ba]">
            <span>Ставка новых инвестиций: <b class="font-medium text-cyan-300">{{ \App\Support\InvestmentTermPresentation::rate($currentTerm->monthly_rate) }}</b></span>
            <span>Капитал доступен к выводу через: <b class="font-medium text-white">{{ \App\Support\InvestmentTermPresentation::lockMonths($currentTerm->lock_months) }}</b></span>
        </div>
    @endif

    <section class="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @foreach($metrics as $index => $metric)<article class="relative overflow-hidden rounded-[18px] border border-white/[.065] bg-[#352e43] p-4"><div class="absolute right-0 top-0 size-20 bg-gradient-to-bl {{ $index % 2 ? 'from-cyan-300/[.065]' : 'from-purple-400/[.085]' }} to-transparent"></div><div class="relative flex items-start justify-between"><div><p class="text-[10px] text-[#9184a3]">{{ $metric[0] }}</p><p class="mt-3 text-[22px] font-semibold tracking-tight text-white">@if(($metric[2] ?? null)==='%'){{ $metric[1] }}<span class="ml-1 text-xs text-cyan-300">%</span>@else{{ \App\Support\MoneyFormatter::format((string)$metric[1]) }}<span class="ml-1 text-[9px] font-normal text-[#746885]">USDT</span>@endif</p></div><span class="size-2 rounded-full {{ $index % 2 ? 'bg-cyan-300' : 'bg-[#b878ec]' }} shadow-[0_0_12px_currentColor]"></span></div></article>@endforeach
    </section>

    @php $tabs=['overview'=>'Обзор','finance'=>'Финансы','accruals'=>'Начисления','payments'=>'Выплаты','wallets'=>'Кошельки','terms'=>'Условия','history'=>'История']; @endphp
    <nav class="mt-5 overflow-x-auto rounded-[16px] border border-white/[.06] bg-[#30283d] p-1.5"><div class="flex min-w-max gap-1">@foreach($tabs as $key=>$label)<button wire:click="selectTab('{{ $key }}')" @disabled(!in_array($key,['overview','finance','accruals','wallets','terms'])) class="rounded-xl px-4 py-2 text-xs transition {{ $activeTab===$key ? 'bg-gradient-to-r from-[#9e62d2]/30 to-cyan-300/10 text-white shadow-[inset_0_0_0_1px_rgba(185,121,236,.2)]' : 'text-[#8f82a1] hover:bg-white/[.03] hover:text-[#c7bad3]' }} disabled:cursor-default disabled:opacity-45">{{ $label }}</button>@endforeach</div></nav>

    @if($activeTab==='overview')
        <section class="mt-4 grid gap-4 xl:grid-cols-2">
            <article class="relative overflow-hidden rounded-[20px] border border-[#b477e7]/15 bg-gradient-to-br from-[#443455] to-[#342b42] p-5 sm:p-6"><div class="absolute -right-16 -top-20 size-52 rounded-full bg-[#ad6ce6]/10 blur-3xl"></div><div class="relative"><div class="flex items-center justify-between"><div><h3 class="text-base font-semibold">Инвестиция</h3><p class="mt-1 text-[10px] text-[#9789a8]">Текущий инвестиционный профиль</p></div><span class="rounded-xl bg-[#ad6ce6]/10 px-3 py-1.5 text-[10px] text-[#c894ed]">{{ $investor->status }}</span></div><div class="mt-6"><p class="text-[10px] uppercase tracking-[.1em] text-[#897b9b]">Капитал</p><p class="mt-1 text-[30px] font-semibold tracking-tight">{{ \App\Support\MoneyFormatter::format($metrics[0][1]) }} <span class="text-xs font-normal text-[#817390]">USDT</span></p></div><dl class="mt-6 grid grid-cols-2 gap-4 border-t border-white/[.07] pt-5 sm:grid-cols-4"><div><dt class="text-[9px] text-[#81748f]">Ставка</dt><dd class="mt-1 text-sm font-medium text-cyan-300">{{ $metrics[1][1] }}%</dd></div><div><dt class="text-[9px] text-[#81748f]">Начало</dt><dd class="mt-1 text-xs text-white">{{ $firstInvestmentDate?->format('d.m.Y') ?: '—' }}</dd></div><div><dt class="text-[9px] text-[#81748f]">Статус</dt><dd class="mt-1 text-xs text-white">{{ $investor->status }}</dd></div><div><dt class="text-[9px] text-[#81748f]">Разблокировка</dt><dd class="mt-1 text-xs text-white">{{ $nearestUnlockDate?->format('d.m.Y') ?: 'Нет блокировки' }}</dd></div></dl></div></article>
            <article class="rounded-[20px] border border-white/[.07] bg-[#342c43] p-5 sm:p-6"><div><h3 class="text-base font-semibold">Финансовый результат</h3><p class="mt-1 text-[10px] text-[#9789a8]">Начисления и доступные средства</p></div><div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-[#2d2639] p-4"><p class="text-[9px] text-[#81748f]">Начислено всего</p><p class="mt-2 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($metrics[4][1]) }}</p></div><div class="rounded-2xl bg-[#2d2639] p-4"><p class="text-[9px] text-[#81748f]">Выплачено</p><p class="mt-2 text-lg font-semibold">{{ \App\Support\MoneyFormatter::format($metrics[5][1]) }}</p></div><div class="rounded-2xl bg-[#2d2639] p-4"><p class="text-[9px] text-[#81748f]">Доступно</p><p class="mt-2 text-lg font-semibold text-cyan-300">{{ \App\Support\MoneyFormatter::format($metrics[6][1]) }}</p></div><div class="rounded-2xl bg-[#2d2639] p-4"><p class="text-[9px] text-[#81748f]">Заблокировано</p><p class="mt-2 text-lg font-semibold text-[#c18def]">{{ \App\Support\MoneyFormatter::format($blockedCapital) }}</p></div></div></article>
        </section>

        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]"><div class="border-b border-white/[.06] px-5 py-4"><h3 class="text-sm font-semibold">Последние операции</h3><p class="mt-1 text-[10px] text-[#847791]">Операции, пополнения и заявки на вывод</p></div><div class="divide-y divide-white/[.045]">@forelse($recentOperations as $item)<div class="flex items-center gap-3 px-4 py-3.5 sm:px-5"><span class="flex size-9 shrink-0 items-center justify-center rounded-xl {{ $item['type']==='deposit_request'||$item['type']==='deposit' ? 'bg-cyan-300/10 text-cyan-300' : 'bg-[#b879ec]/10 text-[#c894ed]' }}">{{ $item['type']==='deposit_request'||$item['type']==='deposit' ? '↓' : '↑' }}</span><div class="min-w-0 flex-1"><p class="truncate text-xs font-medium text-white">{{ str_replace('_',' ',$item['type']) }}</p><p class="mt-0.5 text-[9px] text-[#7f728d]">{{ $item['source'] }} · {{ $item['date']->format('d.m.Y H:i') }}</p></div><div class="text-right"><p class="whitespace-nowrap text-xs font-medium">{{ \App\Support\MoneyFormatter::format($item['amount']) }} USDT</p><p class="mt-0.5 text-[9px] text-[#a58fb7]">{{ $item['status'] }}</p></div></div>@empty<div class="px-5 py-12 text-center text-xs text-[#81748f]">Операций пока нет</div>@endforelse</div></section>

    @elseif($activeTab==='finance')
        <section class="mt-4 space-y-4">
            <article class="overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]"><div class="border-b border-white/[.06] px-5 py-4"><h3 class="text-sm font-semibold">Транши</h3><p class="mt-1 text-[10px] text-[#847791]">Состав инвестиционного капитала</p></div><div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[900px] text-left text-xs"><thead class="border-b border-white/[.06] bg-[#30283d] text-[9px] uppercase tracking-wide text-[#7e718d]"><tr>@foreach(['Дата','Начальная сумма','Остаток','Ставка','Начало начислений','Разблокировка','Статус'] as $h)<th class="px-4 py-3.5">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-white/[.045]">@forelse($lots as $lot)<tr class="hover:bg-white/[.025]"><td class="px-4 py-4 text-[#9588a6]">{{ $lot->received_at->format('d.m.Y') }}</td><td class="px-4 py-4 font-medium text-white">{{ \App\Support\MoneyFormatter::format($lot->original_amount) }}</td><td class="px-4 py-4 font-medium text-white">{{ \App\Support\MoneyFormatter::format($lot->remaining_amount) }}</td><td class="px-4 py-4 text-cyan-300">{{ $lot->monthly_rate }}%</td><td class="px-4 py-4 text-[#9588a6]">{{ $lot->accrual_start_date->format('d.m.Y') }}</td><td class="px-4 py-4 text-[#9588a6]">{{ $lot->unlock_date?->format('d.m.Y') ?: 'Без блокировки' }}</td><td class="px-4 py-4"><span class="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] text-emerald-300">{{ $lot->status }}</span></td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-[#81748f]">Нет траншей</td></tr>@endforelse</tbody></table></div><div class="divide-y divide-white/[.05] md:hidden">@forelse($lots as $lot)<div class="p-4"><div class="flex justify-between"><div><p class="text-[10px] text-[#81748f]">{{ $lot->received_at->format('d.m.Y') }}</p><p class="mt-1 text-sm font-medium">{{ \App\Support\MoneyFormatter::format($lot->remaining_amount) }} USDT</p></div><span class="rounded-full bg-emerald-400/10 px-2 py-1 text-[9px] text-emerald-300">{{ $lot->status }}</span></div><div class="mt-3 grid grid-cols-2 gap-2 text-[10px] text-[#9184a2]"><span>Начальная: {{ \App\Support\MoneyFormatter::format($lot->original_amount) }}</span><span>Ставка: {{ $lot->monthly_rate }}%</span><span>Начисления: {{ $lot->accrual_start_date->format('d.m.Y') }}</span><span>Unlock: {{ $lot->unlock_date?->format('d.m.Y') ?: '—' }}</span></div></div>@empty<div class="p-10 text-center text-xs text-[#81748f]">Нет траншей</div>@endforelse</div></article>

            <article class="overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]"><div class="border-b border-white/[.06] px-5 py-4"><h3 class="text-sm font-semibold">Финансовые операции</h3><p class="mt-1 text-[10px] text-[#847791]">Бухгалтерская история счета</p></div><div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[760px] text-left text-xs"><thead class="border-b border-white/[.06] bg-[#30283d] text-[9px] uppercase tracking-wide text-[#7e718d]"><tr>@foreach(['Дата','Тип','Сумма','Статус','Комментарий'] as $h)<th class="px-4 py-3.5">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-white/[.045]">@forelse($transactions as $item)<tr class="hover:bg-white/[.025]"><td class="px-4 py-4 text-[#9588a6]">{{ $item->effective_date->format('d.m.Y') }}</td><td class="px-4 py-4 text-[#c18def]">{{ $item->type }}</td><td class="px-4 py-4 font-medium text-white">{{ \App\Support\MoneyFormatter::format($item->amount) }}</td><td class="px-4 py-4 text-[#a99bb8]">{{ $item->status }}</td><td class="max-w-sm truncate px-4 py-4 text-[#857891]">{{ $item->comment ?: '—' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-12 text-center text-[#81748f]">Нет операций</td></tr>@endforelse</tbody></table></div><div class="divide-y divide-white/[.05] md:hidden">@forelse($transactions as $item)<div class="p-4"><div class="flex justify-between gap-3"><div><p class="text-xs font-medium text-[#c18def]">{{ $item->type }}</p><p class="mt-1 text-[9px] text-[#7f728d]">{{ $item->effective_date->format('d.m.Y') }} · {{ $item->status }}</p></div><p class="text-xs font-medium">{{ \App\Support\MoneyFormatter::format($item->amount) }} USDT</p></div><p class="mt-3 truncate text-[10px] text-[#8f82a0]">{{ $item->comment ?: 'Без комментария' }}</p></div>@empty<div class="p-10 text-center text-xs text-[#81748f]">Нет операций</div>@endforelse</div></article>
        </section>

    @elseif($activeTab==='wallets')
        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]"><div class="flex flex-col gap-3 border-b border-white/[.06] px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 class="text-sm font-semibold">Платёжные реквизиты для пополнения</h3><p class="mt-1 text-[10px] text-[#847791]">Активные реквизиты фиксируются в новой заявке и не изменяют старые snapshots</p></div><button type="button" wire:click="openPaymentDetailForm" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-4 py-2.5 text-xs font-semibold">Добавить реквизиты</button></div><div class="divide-y divide-white/[.05]">@forelse($paymentDetails as $detail)<div class="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex items-center gap-2"><b class="text-sm">{{ $detail->currency }} · {{ $detail->network }}</b><span class="rounded-full px-2 py-1 text-[9px] {{ $detail->is_active?'bg-emerald-300/10 text-emerald-200':'bg-white/[.05] text-[#9183a2]' }}">{{ $detail->is_active?'Активны':'Неактивны' }}</span></div><code class="mt-2 block break-all text-xs text-cyan-100">{{ $detail->address }}</code>@if($detail->memo)<p class="mt-1 text-xs text-[#9183a2]">Memo/Tag: {{ $detail->memo }}</p>@endif</div><div class="flex gap-2"><button type="button" wire:click="openPaymentDetailForm({{ $detail->id }})" class="cursor-pointer rounded-xl border border-cyan-300/20 px-3 py-2 text-xs text-cyan-100">Изменить</button><button type="button" wire:click="togglePaymentDetail({{ $detail->id }})" class="cursor-pointer rounded-xl border border-white/10 px-3 py-2 text-xs">{{ $detail->is_active?'Деактивировать':'Активировать' }}</button></div></div>@empty<div class="p-8 text-center text-xs text-[#81748f]">Реквизиты ещё не добавлены</div>@endforelse</div></section>
        @if($showPaymentDetailForm)<section class="mt-4 rounded-[20px] border border-white/[.07] bg-[#342c43] p-5"><div class="flex items-center justify-between"><h3 class="font-semibold">{{ $selectedPaymentDetailId?'Изменить реквизиты':'Добавить реквизиты' }}</h3><button type="button" wire:click="closePaymentDetailForm" class="cursor-pointer text-[#9183a2]">✕</button></div><form wire:submit="savePaymentDetail" class="mt-4 space-y-3"><div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-[#9183a2]">Валюта<input wire:model="paymentCurrency" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label><label class="text-xs text-[#9183a2]">Сеть<input wire:model="paymentNetwork" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label></div><label class="block text-xs text-[#9183a2]">Адрес<textarea wire:model="paymentAddress" rows="3" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></textarea></label><label class="block text-xs text-[#9183a2]">Memo/Tag (необязательно)<input wire:model="paymentMemo" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label><label class="flex cursor-pointer items-center gap-2 text-xs"><input type="checkbox" wire:model="paymentIsActive" class="rounded border-white/20 bg-[#2f293e]"> Активны</label>@error('paymentCurrency')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror @error('paymentNetwork')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror @error('paymentAddress')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror<div class="flex justify-end gap-2"><button type="button" wire:click="closePaymentDetailForm" class="cursor-pointer rounded-xl border border-white/10 px-4 py-3 text-sm">Отмена</button><button class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-4 py-3 text-sm font-semibold">Сохранить реквизиты</button></div></form></section>@endif

        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]">
            <div class="border-b border-white/[.06] px-5 py-4"><h3 class="text-sm font-semibold">Действующие кошельки инвестора</h3><p class="mt-1 text-[10px] text-[#847791]">Кошельки, добавленные инвестором и прошедшие проверку</p></div>
            @if($walletConversionMessage)<div class="border-b border-cyan-300/10 bg-cyan-300/[.05] px-5 py-3 text-xs text-cyan-100">{{ $walletConversionMessage }}</div>@endif
            @error('investorWallet')<div class="border-b border-rose-300/10 bg-rose-400/[.06] px-5 py-3 text-xs text-rose-200">{{ $message }}</div>@enderror
            <div class="divide-y divide-white/[.05]">
                @forelse($investorWallets as $wallet)
                    <div class="flex flex-col gap-4 p-4 sm:flex-row sm:items-center sm:justify-between">
                        <div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><b class="text-sm">{{ $wallet->label ?: 'Кошелёк инвестора' }}</b><span class="rounded-full bg-white/[.05] px-2 py-1 text-[9px] text-[#b7a9c4]">{{ \App\Support\WalletPresentation::walletStatus($wallet->status) }}</span></div><p class="mt-1 text-xs text-[#9183a2]">{{ $wallet->currency }} · {{ $wallet->network }}</p><code class="mt-2 block break-all text-xs text-cyan-100">{{ $wallet->address }}</code><div class="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-[10px] text-[#786b89]"><span>Добавлен: {{ $wallet->created_at->format('d.m.Y H:i') }}</span>@if($wallet->approved_at)<span>Одобрен: {{ $wallet->approved_at->format('d.m.Y H:i') }}</span>@endif</div></div>
                        @if($wallet->status === 'approved')
                            <button type="button" wire:click="useWalletForWithdrawal({{ $wallet->id }})" class="shrink-0 cursor-pointer rounded-xl border border-cyan-300/20 px-3 py-2.5 text-xs font-medium text-cyan-100 hover:bg-cyan-300/[.05]">Использовать для вывода</button>
                        @else
                            <span class="shrink-0 rounded-xl border border-white/[.06] px-3 py-2.5 text-xs text-[#786b89]">Доступно после одобрения</span>
                        @endif
                    </div>
                @empty
                    <div class="p-8 text-center text-xs text-[#81748f]">Инвестор ещё не добавлял кошельки</div>
                @endforelse
            </div>
        </section>

        <section class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]">
            <div class="flex flex-col gap-3 border-b border-white/[.06] px-5 py-4 sm:flex-row sm:items-center sm:justify-between">
                <div><h3 class="text-sm font-semibold">Платёжные реквизиты для вывода</h3><p class="mt-1 text-[10px] text-[#847791]">Постоянные реквизиты, на которые CEO Money отправляет средства инвестору</p></div>
                <button type="button" wire:click="openWithdrawalDetailForm" class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-4 py-2.5 text-xs font-semibold">Добавить реквизиты</button>
            </div>
            <div class="divide-y divide-white/[.05]">
                @forelse($withdrawalDetails as $detail)
                    <div class="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between">
                        <div><div class="flex items-center gap-2"><b class="text-sm">{{ $detail->currency }} · {{ $detail->network }}</b><span class="rounded-full px-2 py-1 text-[9px] {{ $detail->is_active?'bg-emerald-300/10 text-emerald-200':'bg-white/[.05] text-[#9183a2]' }}">{{ $detail->is_active?'Активны':'Неактивны' }}</span></div><code class="mt-2 block break-all text-xs text-cyan-100">{{ $detail->address }}</code>@if($detail->memo)<p class="mt-1 text-xs text-[#9183a2]">Memo/Tag: {{ $detail->memo }}</p>@endif</div>
                        <div class="flex gap-2"><button type="button" wire:click="openWithdrawalDetailForm({{ $detail->id }})" class="cursor-pointer rounded-xl border border-cyan-300/20 px-3 py-2 text-xs text-cyan-100">Изменить</button><button type="button" wire:click="toggleWithdrawalDetail({{ $detail->id }})" class="cursor-pointer rounded-xl border border-white/10 px-3 py-2 text-xs">{{ $detail->is_active?'Деактивировать':'Активировать' }}</button></div>
                    </div>
                @empty
                    <div class="p-8 text-center text-xs text-[#81748f]">Реквизиты для вывода ещё не добавлены</div>
                @endforelse
            </div>
        </section>
        @if($showWithdrawalDetailForm)
            <section class="mt-4 rounded-[20px] border border-white/[.07] bg-[#342c43] p-5"><div class="flex items-center justify-between"><h3 class="font-semibold">{{ $selectedWithdrawalDetailId?'Изменить реквизиты для вывода':'Добавить реквизиты для вывода' }}</h3><button type="button" wire:click="closeWithdrawalDetailForm" class="cursor-pointer text-[#9183a2]">✕</button></div><form wire:submit="saveWithdrawalDetail" class="mt-4 space-y-3"><div class="grid gap-3 sm:grid-cols-2"><label class="text-xs text-[#9183a2]">Валюта<input wire:model="withdrawalDetailCurrency" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label><label class="text-xs text-[#9183a2]">Сеть<input wire:model="withdrawalDetailNetwork" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label></div><label class="block text-xs text-[#9183a2]">Адрес<textarea wire:model="withdrawalDetailAddress" rows="3" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></textarea></label><label class="block text-xs text-[#9183a2]">Memo/Tag (необязательно)<input wire:model="withdrawalDetailMemo" class="mt-1 w-full rounded-xl border border-white/10 bg-[#2f293e] px-3 py-2.5 text-white"></label><label class="flex cursor-pointer items-center gap-2 text-xs"><input type="checkbox" wire:model="withdrawalDetailIsActive" class="rounded border-white/20 bg-[#2f293e]"> Активны</label>@error('withdrawalDetailCurrency')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror @error('withdrawalDetailNetwork')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror @error('withdrawalDetailAddress')<p class="text-xs text-rose-200">{{ $message }}</p>@enderror<div class="flex justify-end gap-2"><button type="button" wire:click="closeWithdrawalDetailForm" class="cursor-pointer rounded-xl border border-white/10 px-4 py-3 text-sm">Отмена</button><button class="cursor-pointer rounded-xl bg-gradient-to-r from-[#ac6aec] to-[#6875e9] px-4 py-3 text-sm font-semibold">Сохранить реквизиты</button></div></form></section>
        @endif
    @elseif($activeTab==='terms')
        @include('livewire.admin.investors.partials.terms')
    @elseif($activeTab==='accruals')
        <section class="mt-4"><div class="grid gap-3 sm:grid-cols-3">@foreach(['Начислено сегодня','За месяц','За всё время'] as $i=>$label)<article class="rounded-[18px] border border-white/[.065] bg-[#352e43] p-4"><p class="text-[10px] text-[#9184a3]">{{ $label }}</p><p class="mt-3 text-[22px] font-semibold">{{ \App\Support\MoneyFormatter::format($accrualTotals[$i]) }} <span class="text-[9px] font-normal text-[#746885]">USDT</span></p></article>@endforeach</div>
            <article class="mt-4 overflow-hidden rounded-[20px] border border-white/[.07] bg-[#342c43]"><div class="flex items-center justify-between border-b border-white/[.06] px-4 py-3.5 sm:px-5"><button wire:click="previousMonth" aria-label="Предыдущий месяц" class="flex size-9 items-center justify-center rounded-xl bg-[#292236] text-[#a99bb8] hover:text-white">←</button><div class="text-center"><h3 class="text-sm font-semibold capitalize">{{ $selectedMonthLabel }}</h3><p class="mt-0.5 text-[9px] text-[#7f728d]">Ежедневные начисления</p></div><button wire:click="nextMonth" aria-label="Следующий месяц" class="flex size-9 items-center justify-center rounded-xl bg-[#292236] text-[#a99bb8] hover:text-white">→</button></div>
                <div class="border-b border-white/[.06] p-4 sm:p-5"><div class="relative h-[160px] overflow-hidden rounded-2xl bg-[#2c2538] p-2"><div class="absolute inset-3 grid grid-rows-4"><i class="border-t border-white/[.045]"></i><i class="border-t border-white/[.045]"></i><i class="border-t border-white/[.045]"></i><i class="border-t border-white/[.045]"></i></div><svg viewBox="0 0 720 150" preserveAspectRatio="none" class="relative h-full w-full" aria-label="График начислений за месяц"><defs><filter id="accrualGlow"><feGaussianBlur stdDeviation="2" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><polyline points="{{ $accrualChartPoints }}" fill="none" stroke="#70d7e8" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" filter="url(#accrualGlow)"/></svg></div></div>
                <div class="hidden overflow-x-auto md:block"><table class="w-full min-w-[900px] text-left text-xs"><thead class="border-b border-white/[.06] bg-[#30283d] text-[9px] uppercase tracking-wide text-[#7e718d]"><tr>@foreach(['Дата','База','Ставка','Дней','Начислено','Корректировка','Итого'] as $h)<th class="px-4 py-3.5">{{ $h }}</th>@endforeach</tr></thead><tbody class="divide-y divide-white/[.045]">@forelse($accruals as $item)<tr class="hover:bg-white/[.025]"><td class="px-4 py-4 text-[#9588a6]">{{ $item->accrual_date->format('d.m.Y') }}</td><td class="px-4 py-4">{{ \App\Support\MoneyFormatter::format($item->principal_amount) }}</td><td class="px-4 py-4 text-cyan-300">{{ $item->monthly_rate }}%</td><td class="px-4 py-4 text-[#9588a6]">{{ $item->days_in_month }}</td><td class="px-4 py-4">{{ \App\Support\MoneyFormatter::format($item->calculated_amount) }}</td><td class="px-4 py-4 text-[#c18def]">{{ \App\Support\MoneyFormatter::format($item->adjustment_amount) }}</td><td class="px-4 py-4 font-medium text-white">{{ \App\Support\MoneyFormatter::format($item->final_amount) }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-12 text-center text-[#81748f]">Нет начислений за выбранный месяц</td></tr>@endforelse</tbody></table></div><div class="divide-y divide-white/[.05] md:hidden">@forelse($accruals as $item)<div class="p-4"><div class="flex justify-between"><p class="text-xs font-medium">{{ $item->accrual_date->format('d.m.Y') }}</p><p class="text-xs font-semibold text-cyan-300">{{ \App\Support\MoneyFormatter::format($item->final_amount) }} USDT</p></div><div class="mt-3 grid grid-cols-2 gap-2 text-[10px] text-[#9184a2]"><span>База: {{ \App\Support\MoneyFormatter::format($item->principal_amount) }}</span><span>Ставка: {{ $item->monthly_rate }}%</span><span>Начислено: {{ \App\Support\MoneyFormatter::format($item->calculated_amount) }}</span><span>Коррекция: {{ \App\Support\MoneyFormatter::format($item->adjustment_amount) }}</span></div></div>@empty<div class="p-10 text-center text-xs text-[#81748f]">Нет начислений</div>@endforelse</div>
            </article>
        </section>
    @endif
</div>
